#!/usr/bin/env python3
"""The CHANGELOG needs an ENTRANCE — one table, generated, never typed (autosound-hub HUB-043).

A reader opens this file with one question: *what changes for me if I upgrade?* The answer is in
there — every note carries an **Upgrading** line when there is something to know — but on
2026-09-06 finding it meant reading 3 297 lines / 292 KB across 72 version sections, some of them
90 lines long. The doctrine of what a version number means stays in `CHANGELOG.md` (it is about how
to write a note, and it lives there correctly); what was missing was the way in.

So: a table of every version — number, date, the one-line summary the heading already carries, and
whether that section has an Upgrading note — generated from the headings themselves, between
`<!-- changelog-index:start -->` and `<!-- changelog-index:end -->`. Generated and not written,
because an index maintained by hand is a second source of truth about which versions exist, and it
is wrong the first time someone forgets it. `--check` is the version the test suite runs: it
regenerates and compares, so a new version note without an index row fails.

Versions up to v3.0.20 live in `docs/changelog/archive-v1.0.0-v3.0.20.md`; the table spans BOTH
files, so a version is looked up in one place no matter which file holds it.

The limit, named: the links are GitHub's own heading anchors, computed here by GitHub's documented
rule (lowercase, drop everything that is not a word character, space or hyphen, spaces to hyphens).
`--check` proves every anchor comes from a heading that exists in the file it points at; it cannot
prove GitHub renders that anchor the same way, because that is not knowable offline.

Run: `scripts/changelog-index.py` (writes), `--check` (fails on a stale table), `--selftest`.
stdlib only.
"""
from __future__ import annotations

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LIVE = "CHANGELOG.md"
ARCHIVE = os.path.join("docs", "changelog", "archive-v1.0.0-v3.0.20.md")
START = "<!-- changelog-index:start -->"
END = "<!-- changelog-index:end -->"
# `## [v3.0.46] — 2026-09-06 · one line about what changed`
VERSION_HEAD = re.compile(r"^## \[(?P<ver>[^\]]+)\](?:\s*[—-]\s*(?P<date>\d{4}-\d{2}-\d{2}))?"
                          r"(?:\s*·\s*(?P<summary>.+))?$")
UPGRADING = "**Upgrading:**"


def anchor(heading_line: str) -> str:
    """GitHub's heading anchor for a `## ...` line."""
    text = heading_line.lstrip("#").strip().lower()
    text = re.sub(r"[^\w\s-]", "", text)
    return text.replace(" ", "-")


def versions(root: str, rel: str) -> list[dict]:
    """Every version section of one file, in file order, with its Upgrading flag."""
    path = os.path.join(root, rel)
    if not os.path.isfile(path):
        return []
    lines = open(path, encoding="utf-8").read().splitlines()
    found = []
    for i, line in enumerate(lines):
        m = VERSION_HEAD.match(line)
        if not m:
            continue
        if found:
            found[-1]["body_end"] = i
        found.append({"ver": m.group("ver"), "date": m.group("date") or "",
                      "summary": (m.group("summary") or "").strip(),
                      "anchor": anchor(line), "file": rel, "body_start": i + 1,
                      "body_end": len(lines)})
    for v in found:
        body = "\n".join(lines[v["body_start"]:v["body_end"]])
        v["upgrading"] = UPGRADING in body
    return found


def render(root: str) -> str:
    rows = versions(root, LIVE) + versions(root, ARCHIVE)
    out = [START,
           "## Index — every version, newest first",
           "",
           "Generated by `scripts/changelog-index.py` (the test suite fails on a stale table — do "
           "not edit by hand).",
           "**Upgrading** marks a section that carries a note about what changes for a consumer; "
           "versions up to v3.0.20 are in "
           "[`docs/changelog/archive-v1.0.0-v3.0.20.md`](docs/changelog/archive-v1.0.0-v3.0.20.md).",
           "",
           "| Version | Date | What changed | Upgrading |",
           "| :--- | :--- | :--- | :---: |"]
    for v in rows:
        href = ("#" + v["anchor"]) if v["file"] == LIVE else \
            (ARCHIVE.replace(os.sep, "/") + "#" + v["anchor"])
        summary = v["summary"].replace("|", "\\|") or "—"
        out.append(f"| [{v['ver']}]({href}) | {v['date'] or '—'} | {summary} | "
                   f"{'yes' if v['upgrading'] else '—'} |")
    out += ["", f"{len(rows)} versions.", END]
    return "\n".join(out) + "\n"


def _splice(src: str, block: str) -> str:
    """Replace whatever stands between the markers (inclusive) with `block`."""
    i, j = src.find(START), src.find(END)
    if i < 0 or j < 0:
        raise SystemExit(f"{LIVE}: the markers {START} / {END} are not both there — the index has "
                         f"nowhere to go")
    tail = src[j + len(END):]
    if tail.startswith("\n"):
        tail = tail[1:]                  # `block` already ends with its own newline
    return src[:i] + block + tail


def write(root: str) -> int:
    path = os.path.join(root, LIVE)
    src = open(path, encoding="utf-8").read()
    new = _splice(src, render(root))
    if new == src:
        print("index already current — nothing written")
        return 0
    open(path, "w", encoding="utf-8").write(new)
    print(f"index written into {LIVE}")
    return 0


def check(root: str) -> int:
    path = os.path.join(root, LIVE)
    src = open(path, encoding="utf-8").read()
    want = render(root)
    i, j = src.find(START), src.find(END)
    if i < 0 or j < 0:
        print(f"{LIVE}: no index block — run scripts/changelog-index.py", file=sys.stderr)
        return 1
    have = src[i:j + len(END)] + "\n"
    if have != want:
        heads = len(versions(root, LIVE)) + len(versions(root, ARCHIVE))
        rows = len([ln for ln in have.splitlines() if ln.startswith("| [")])
        print(f"{LIVE}: the index is stale — {rows} row(s) for {heads} version heading(s). "
              f"Run scripts/changelog-index.py", file=sys.stderr)
        return 1
    # every anchor must come from a heading that really is in the file it points at
    for v in versions(root, LIVE) + versions(root, ARCHIVE):
        body = open(os.path.join(root, v["file"]), encoding="utf-8").read()
        if f"[{v['ver']}]" not in body:
            print(f"{v['file']}: index row {v['ver']} points at a heading that is not there",
                  file=sys.stderr)
            return 1
    n = len([ln for ln in want.splitlines() if ln.startswith("| [")])
    print(f"changelog index OK — {n} versions in the table, one row per heading across "
          f"{LIVE} + the archive")
    return 0


def _selftest() -> int:
    import shutil
    import tempfile
    tmp = tempfile.mkdtemp(prefix="changelog_index_")
    try:
        os.makedirs(os.path.join(tmp, os.path.dirname(ARCHIVE)))
        open(os.path.join(tmp, LIVE), "w", encoding="utf-8").write(
            f"# Changelog\n\n{START}\n{END}\n\n"
            "## [v9.9.1] — 2026-09-09 · a thing changed\n\n> **Upgrading:** read this.\n\ntext\n\n"
            "## [v9.9.0] — 2026-09-08 · another thing\n\nno note here\n")
        open(os.path.join(tmp, ARCHIVE), "w", encoding="utf-8").write(
            "# archive\n\n## [v1.0.0] — 2026-06-13\n\nold\n")

        assert check(tmp) == 1, "an empty block must be caught as stale"
        assert write(tmp) == 0
        assert check(tmp) == 0, "a freshly written index must pass"
        src = open(os.path.join(tmp, LIVE), encoding="utf-8").read()
        assert "| [v9.9.1](#v991--2026-09-09--a-thing-changed) | 2026-09-09 |" in src, src
        assert src.count("| yes |") == 1, "only the section with an Upgrading note is marked"
        assert ARCHIVE.replace(os.sep, "/") + "#v100--2026-06-13" in src, "archive link missing"
        assert "3 versions." in src

        # a new version note without regenerating the index fails
        with open(os.path.join(tmp, LIVE), "a", encoding="utf-8") as fh:
            fh.write("\n## [v9.9.2] — 2026-09-10 · newest\n\nbody\n")
        assert check(tmp) == 1, "a version added after the index must fail the check"
        assert write(tmp) == 0 and check(tmp) == 0

        # and the repository itself, which is the point of the whole file
        assert check(ROOT) == 0, "the tree must be clean, or the selftest measures a fake"
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    print("selftest OK — an empty index, a stale one and a version added after it are each caught; "
          "the Upgrading flag follows the note, and an archived version links into the archive")
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the table is stale")
    parser.add_argument("--selftest", action="store_true", help="check the checker's own mechanics")
    parser.add_argument("--root", default=ROOT, help="the repository root")
    args = parser.parse_args(argv)
    if args.selftest:
        return _selftest()
    return check(args.root) if args.check else write(args.root)


if __name__ == "__main__":
    sys.path.insert(0, os.path.join(ROOT, "skills", "autosound-tuning", "rew_tool"))
    import console
    console.install()
    sys.exit(main())
