"""Versioned hard-params DSP state — the anti-drift anchor AND the experimentation engine.

The single source of truth is one JSON per snapshot (`v_NNN.json`) under `<root>/<preset>/`.
A human-readable Markdown settings sheet is GENERATED from that JSON (`render`); it is never
hand-edited. Editing a rendered view instead of the source is the split-artifact trap
(gains-lived-in-a-screenshot while EQ-lived-in-.req → a careful reader mis-concluded "no gain
change") that this module exists to kill: one file per snapshot holds crossovers + gains + TA +
polarity + EQ pointers together, so nobody ever reads a partial picture.

Why versioned: the same file that stops drift (write-after-every-change, read-before-edit) is what
makes weird ideas cheap to try — a snapshot is a diff/A-B/revert away, so experimentation costs
one command. Stability and freedom are the same mechanism, not opposites.

Layout
    <root>/<preset>/v_001.json, v_002.json, ...   immutable snapshots
    <root>/<preset>/HEAD                           text file: the current version name

Design invariants
    * ms is the CANONICAL delay unit; samples are DERIVED from the preset's sample_rate at render
      time and never stored. Entering 96 kHz samples into a 48 kHz DSP doubles the physical delay
      and ruins alignment — so the file commits to ms, and samples are a view.
    * status lifecycle (AD-1): proposed -> applied -> measured. The file is the source of truth for
      INTENT + ATTESTED-APPLIED, NOT a guaranteed device mirror; device-truth is the latest
      measurement. The design claims nothing more.
    * snapshot() VALIDATES before writing and refuses on malformed state — a deterministic gate in
      embryo (a confabulated/garbage state can't be silently banked).
    * revert() is forward-only: it writes a NEW snapshot copying an old one, never destroys history.

Schema v3 (2026-07-31, the 3.0 format break) — two changes on top of v2 below:
    * **Identity left this file.** `slot`/`descr`/`role`/`order`/`hidden`/`tag_value` live in
      `project.json` (`channels[]`, and `hardware.controls` for `tag_value`); a row here carries
      only what can differ between two snapshots of the same install. `validate` REFUSES a row
      still carrying them rather than dropping them silently — see `MOVED_TO_PROJECT_JSON`.
    * **Every snapshot stamps `project_rev`** (SCR-024): which revision of those facts the values
      were dialled against, so joining an old snapshot to today's `project.json` can be detected
      instead of silently relabelling history when a driver gets replaced.
`state/migrate.py` moves a 2.x project across; nothing here reads 2.x files.

Schema v2 (2026-07-29, autosound-tcc sync): the ledger is TIER-AWARE, not `channels`-only. A tier
is any top-level key holding a dict of row-dicts -- `channels` (the required physical-outputs
tier, unchanged key name) plus any other profile-declared tier a project's DSP has (e.g.
`virtual_channels`). `validate`/`diff_states`/`apply.propose` all walk every tier present; only
`channels` carries the strict required-field list (hp/lp/gain_db/ta_ms/polarity) since it is the
one tier every DSP profile has. A NEW tier must exist as a (possibly empty) top-level key before a
delta can address it by name -- intake seeds every profile-declared tier, even empty, at the first
snapshot; see `tier_names()`. `eq` bands are now STRUCTURED OBJECTS
(`{"type": "PK", "f": 1000, "gain_db": -9, "q": 2, "bypass": false}`), not strings -- the old
inline string form is display-only now, generated by `eq_str()`. `schema_version` is stamped on
every snapshot going forward.
"""

import argparse
import copy
import datetime
import json
import os
import re

# ── schema ──────────────────────────────────────────────────────────────────
# One number across every machine file (see `project.py`'s own note). 3 is the format break.
SCHEMA_VERSION = 3
POLARITIES = ("NORM", "INV")
STATUSES = ("proposed", "applied", "measured")
EQ_TYPES = ("PK", "LSH", "HSH", "APF1", "APF2")
CHANNEL_FIELDS = (
    "tag", "mute", "off",
    "hp", "lp", "gain_db", "ta_ms", "polarity", "phase_deg", "eq", "eq_ptr", "status",
)
# Channel IDENTITY is NOT here (schema v3, SCR-001): `slot`, `descr`, `role`, `order`, `hidden`
# and `tag_value` moved to `project.json` -- `channels[]` for the first five, `hardware.controls`
# for `tag_value` (SCR-017, a knob position is a property of the DEVICE, constant across presets).
# A consumer joins the two on the channel `code`; `autosound-tcc`'s `state/dsp_state.py` does
# exactly that. What stays here is what changes from one snapshot to the next -- the test that
# decided the split. `tag` stays because it is structural: WHICH control affects this row.
# In v2 these lived in both files at once, which is a fact with two homes and no arbiter; v3
# removes them from this side rather than deprecating them, and `state/migrate.py` moves the
# values across for a 2.x project.
#
# `eq` (a list of structured band objects, schema v2) coexists with the older `eq_ptr` (a pointer
# to a `.req` export file) rather than replacing it: they answer different questions -- `eq_ptr`
# says where the authoritative export lives, `eq` carries the bands themselves so a reader needs
# no second file. Listing `eq` here only makes it a legal field to carry/merge/diff; DERIVING
# bands from measurement data is separate, unbuilt work.
TOP_REQUIRED = ("preset", "sample_rate", "channels")
# Top-level keys that hold project/preset METADATA, not a tier of rows, even though some are
# dict-valued (`roles` is {role: name}, `provenance` may be a dict OR a free sentence) -- every
# OTHER top-level key whose value is a dict is a tier (`tier_names()`), the same convention
# `autosound-tcc`'s `ProjectView.from_dict` already reads by (physical_outputs -> `channels`, any
# other profile group id -> a same-named top-level key).
_NON_TIER_KEYS = {
    "preset", "version", "created", "schema_version", "sample_rate", "target", "roles",
    "provenance", "banked_ear_verdicts", "virtual_eq_ptr", "note", "features", "slot_label",
    "save",
}
_VER_RE = re.compile(r"^v_(\d{3,})$")
_EQ_GAIN_RE = re.compile(r"^[+-][\d.]+$")
_EQ_Q_RE = re.compile(r"^[Qq]([\d.]+)$")
_EQ_NUM_RE = re.compile(r"^[\d.]+$")
_EQ_TYPE_ALIASES = {"LS": "LSH", "HS": "HSH"}  # shorthand seen in hand-authored v1 ledgers


def tier_names(state):
    """Every tier key present in `state`: `channels` (always, even if absent -- callers checking
    membership still get the right answer from `validate`) plus any other top-level key whose
    value is a dict-of-dicts (e.g. `virtual_channels`). An EMPTY tier dict still counts -- that is
    what lets intake seed a tier before the first row exists in it (see the schema-v2 note above)."""
    out = ["channels"]
    for k, v in state.items():
        if k in _NON_TIER_KEYS or k == "channels":
            continue
        # A dict here IS a tier. It used to have to be a dict of dicts, so ONE stray value
        # ("comment": "temp note") demoted the whole key to unknown metadata — and `validate`
        # never looks at unknown keys, so the tier passed validation and then vanished from
        # `validate`, `diff_states` and `render` at once. That is the split-artifact failure this
        # module documents as killed, re-armed by a single line (found by audit, 2026-08-12).
        # The bad ROW is now `validate`'s problem, which is the right place for it.
        if isinstance(v, dict):
            out.append(k)
    return out


def eq_band_from_str(raw):
    """Parse one legacy inline EQ band string (e.g. `"PK 1000 -9 Q2"`) into a v2 band object.

    Migration-only (`migrate.py`) -- the band OBJECT is canonical going forward; this exists so
    the two hand-authored v1 ledgers upgrade without hand-transcription. Tolerates the `LS`/`HS`
    shorthand actually used in those files (canonical types are `EQ_TYPES`).
    """
    tokens = raw.split()
    if not tokens:
        raise ValueError("empty EQ band string")
    band_type = _EQ_TYPE_ALIASES.get(tokens[0], tokens[0])
    freq_hz = gain_db = q = None
    for tok in tokens[1:]:
        if freq_hz is None and _EQ_NUM_RE.match(tok):
            freq_hz = float(tok)
        elif _EQ_GAIN_RE.match(tok):
            gain_db = float(tok)
        elif _EQ_Q_RE.match(tok):
            q = float(_EQ_Q_RE.match(tok).group(1))
    if freq_hz is None:
        raise ValueError(f"could not parse a frequency from EQ band {raw!r}")
    band = {"type": band_type, "f": freq_hz}
    if gain_db is not None:
        band["gain_db"] = gain_db
    if q is not None:
        band["q"] = q
    return band


def eq_band_str(band):
    """One band object rendered as the old inline string (e.g. `"PK 1000 -9 Q2"`) -- display-only
    now (chat output, the settings sheet, the Helix-export path); the band object is canonical."""
    parts = [band["type"], f"{band['f']:g}"]
    if band.get("gain_db") is not None:
        parts.append(f"{band['gain_db']:+g}")
    if band.get("q") is not None:
        parts.append(f"Q{band['q']:g}")
    if band.get("bypass"):
        parts.append("(bypass)")
    return " ".join(parts)


def eq_str(bands):
    """A whole `eq` list rendered as display strings, oldest-format-compatible, in order."""
    return [eq_band_str(b) for b in (bands or [])]


def _validate_filter(name, ch_name, f):
    """A crossover leg is null / "OFF" (disabled) or {f, type, slope}."""
    if f is None or f == "OFF":
        return
    if not isinstance(f, dict) or "f" not in f:
        raise ValueError(f"{ch_name}.{name}: expected null/'OFF' or {{f,type,slope}}, got {f!r}")
    if not isinstance(f["f"], (int, float)) or f["f"] <= 0:
        raise ValueError(f"{ch_name}.{name}.f must be a positive Hz, got {f.get('f')!r}")


def _validate_eq(tier, ch_name, eq):
    if not isinstance(eq, list):
        raise ValueError(f"{tier}.{ch_name}.eq must be a list of band objects, got {eq!r}")
    seen_i = set()
    for idx, band in enumerate(eq):
        if not isinstance(band, dict):
            raise ValueError(f"{tier}.{ch_name}.eq[{idx}] must be an object, got {band!r}")
        if band.get("type") not in EQ_TYPES:
            raise ValueError(f"{tier}.{ch_name}.eq[{idx}].type must be one of {EQ_TYPES}, "
                             f"got {band.get('type')!r}")
        f = band.get("f")
        if not isinstance(f, (int, float)) or isinstance(f, bool) or f <= 0:
            raise ValueError(f"{tier}.{ch_name}.eq[{idx}].f must be a positive Hz, got {f!r}")
        for numf in ("gain_db", "q"):
            if numf in band and band[numf] is not None and not isinstance(band[numf], (int, float)):
                raise ValueError(f"{tier}.{ch_name}.eq[{idx}].{numf} must be a number if present, "
                                 f"got {band[numf]!r}")
        if "bypass" in band and band["bypass"] is not None and not isinstance(band["bypass"], bool):
            raise ValueError(f"{tier}.{ch_name}.eq[{idx}].bypass must be a bool if present, "
                             f"got {band['bypass']!r}")
        if "i" in band and band["i"] is not None:
            if isinstance(band["i"], bool) or not isinstance(band["i"], int):
                raise ValueError(f"{tier}.{ch_name}.eq[{idx}].i must be an int if present, "
                                 f"got {band['i']!r}")
            if band["i"] in seen_i:
                raise ValueError(f"{tier}.{ch_name}.eq: duplicate band index i={band['i']!r}")
            seen_i.add(band["i"])


#: Identity fields a v2 row carried that `project.json` owns in v3 (SCR-001/017). Rejected rather
#: than ignored: silently dropping them on write would make a migration look like it worked while
#: losing the only copy of a `descr` nobody had entered into `project.json` yet.
#:
#: `helix_ch` is the one that RENAMED on the way out, and it is the one that matters most: it is
#: the DSP output letter, the thing the Arbiter types into the processor. It was also the only
#: identity field the RELEASED 2.x line ever wrote — `slot`/`descr`/`role`/`order`/`hidden`/
#: `tag_value` appear nowhere in v2.8.1 and came from the development states between the releases.
#: Leaving it off this list meant a real v2.8.1 ledger sailed through validation, migrated
#: "successfully", and arrived with an empty Slot column (2026-08-12).
def migration_command(project_dir="<project-dir>"):
    """The migration, as a line somebody can paste — see `state/process.py::migration_command`.
    Duplicated rather than imported: this module is loaded by consumers that put neither `state/`
    nor its parent on `sys.path`, and a hint that cannot be produced is worse than a long line."""
    here = os.path.dirname(os.path.abspath(__file__))
    return f"python3 {os.path.join(here, 'migrate.py')} {project_dir} --into <new-project-dir>"


MOVED_TO_PROJECT_JSON = {
    "helix_ch": "channels[].slot",
    "slot": "channels[].slot",
    "descr": "channels[].descr",
    "role": "channels[].role",
    "order": "channels[].order",
    "hidden": "channels[].hidden",
    "tag_value": "hardware.controls[<tag>].value",
}


def _project_json(project_dir):
    try:
        with open(os.path.join(project_dir, "project.json"), encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def project_channels(project_dir):
    """`project.json`'s `channels[]` keyed by every name a ledger row might use — SCR-001/039.

    A ledger row's key is the channel's **id** (SCR-039), which for every project that has never
    renamed anything is simply its code — so the common case is unchanged. After a rename the same
    row is reachable under three keys: the id the snapshots were written with, the name it goes by
    now, and any name it went by before. A snapshot is immutable, so the old key is the only one it
    will ever have, and a reader that could not resolve it would render a channel it has full
    identity for as unknown.

    Absent file, absent key, or an entry with neither code nor id all read as "not captured": a
    project mid-intake renders a `—` in the Slot column, which is honest, rather than failing to
    render.
    """
    channels = _project_json(project_dir).get("channels")
    if not isinstance(channels, list):
        return {}
    out = {}
    for c in channels:
        if not isinstance(c, dict):
            continue
        keys = [c.get("id"), c.get("code")] + list(c.get("previous_names") or [])
        for key in keys:
            # A live code wins over another channel's history: `setdefault` would let whichever row
            # came first in the file own the name, which is row order deciding identity.
            if key and (str(key) not in out or key == c.get("code")):
                out[str(key)] = c
    return out


def processing_rate(project_dir):
    """The DSP's PROCESSING rate from the project's `dsp_profile.json` (either key: the canonical
    `dsp_processing_rate_hz` or the legacy `sample_rate_hz`), or None.

    The settings sheet derives its samples column from THIS, not from the snapshot's own recorded
    rate (the user's ruling, 2026-08-25): the snapshot's number is what was believed at bank time,
    and if the profile is later corrected, the sheet must follow the profile -- the sheet is what
    the Arbiter types into the DSP, and the DSP runs at the profile's rate.
    """
    path = os.path.join(project_dir or "", "dsp_profile.json")
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return None
    body = data.get("dsp_profile") if isinstance(data.get("dsp_profile"), dict) else data
    if not isinstance(body, dict):
        return None
    v = body.get("dsp_processing_rate_hz")
    v = v if v is not None else body.get("sample_rate_hz")
    return v if isinstance(v, (int, float)) and not isinstance(v, bool) and v > 0 else None


def current_target(project_dir, preset):
    """The CURRENT active target curve for `preset`, from `process/process-state.json`'s `targets`.

    Two different facts wear the name "target" and this untangles them (2026-08-25, a live project's
    header rendered `—` after the tuner had set the curve): a **snapshot's** `target` is what that
    version was DESIGNED AGAINST — historical, per-version, immutable with the snapshot; the process
    journal's `targets[preset]` is the CURRENT pointer, which `process.py target` moves. The gate and
    the plan audit read the pointer; the settings sheet must show the pointer too, or the documented
    `process target` updates a home the sheet never reads. Returns None when there is no process dir
    or no pointer yet — the caller falls back to the snapshot's own `target`.
    """
    path = os.path.join(project_dir or "", "process", "process-state.json")
    try:
        with open(path, encoding="utf-8") as fh:
            targets = (json.load(fh) or {}).get("targets") or {}
    except (OSError, ValueError):
        return None
    v = targets.get(preset)
    return v if isinstance(v, str) and v.strip() else None


def _project_rev(project_dir):
    """`project.json`'s current `project_rev`, or 0 if this project has no facts file yet.

    Read as plain JSON rather than through `project.py`: this module lives one directory down and
    is imported under a synthetic name by consumers, and one integer is not worth a cross-package
    import that would only ever be used here.
    """
    rev = _project_json(project_dir).get("project_rev")
    return rev if isinstance(rev, int) and not isinstance(rev, bool) and rev >= 0 else 0


def _validate_row(tier, ch_name, ch, required):
    """One tier row's fields, generic across tiers. `required` (only non-empty for `channels`,
    the one tier every DSP profile has) lists fields that must be KEYS on the row; everything else
    is type-checked only when present -- a virtual-channel row with no `hp`/`lp` at all is not an
    error, a `hp` that IS there but malformed is."""
    missing = [f for f in required if f not in ch]
    if missing:
        raise ValueError(f"{tier}.{ch_name!r} missing {missing}")
    moved = sorted(f for f in MOVED_TO_PROJECT_JSON if f in ch)
    if moved:
        where = ", ".join(f"{f} -> project.json {MOVED_TO_PROJECT_JSON[f]}" for f in moved)
        raise ValueError(
            f"{tier}.{ch_name!r} carries identity field(s) that moved out of the ledger in schema "
            f"v{SCHEMA_VERSION} ({where}) -- 2.x snapshot. Migrate once:\n    "
            + migration_command()
        )
    if "hp" in ch:
        _validate_filter("hp", ch_name, ch["hp"])
    if "lp" in ch:
        _validate_filter("lp", ch_name, ch["lp"])
    if "gain_db" in ch and ch["gain_db"] is not None and not isinstance(ch["gain_db"], (int, float)):
        raise ValueError(f"{tier}.{ch_name}.gain_db must be a number, got {ch['gain_db']!r}")
    if "ta_ms" in ch and ch["ta_ms"] is not None and not isinstance(ch["ta_ms"], (int, float)):
        raise ValueError(f"{tier}.{ch_name}.ta_ms must be a number (ms is canonical), got {ch['ta_ms']!r}")
    if "polarity" in ch and ch["polarity"] is not None and ch["polarity"] not in POLARITIES:
        raise ValueError(f"{tier}.{ch_name}.polarity must be one of {POLARITIES}, got {ch['polarity']!r}")
    st = ch.get("status")
    if st is not None and st not in STATUSES:
        raise ValueError(f"{tier}.{ch_name}.status must be one of {STATUSES}, got {st!r}")
    for flag in ("mute", "off"):
        if flag in ch and ch[flag] is not None and not isinstance(ch[flag], bool):
            raise ValueError(f"{tier}.{ch_name}.{flag} must be a bool if present, got {ch[flag]!r}")
    if "eq" in ch and ch["eq"] is not None:
        _validate_eq(tier, ch_name, ch["eq"])


def validate(state):
    """Raise ValueError on malformed state; return the state unchanged if OK.

    Walks every TIER (`tier_names`), not just `channels` -- schema v2 (2026-07-29). Only `channels`
    (the physical-outputs tier every DSP profile has) carries the strict required-field list;
    other tiers (e.g. `virtual_channels`) are validated leniently, same "strict on silent/expensive
    errors, lenient on the rest" split as before. `note`/`provenance` stay unchecked free-text.
    """
    for k in TOP_REQUIRED:
        if k not in state:
            raise ValueError(f"state missing required key {k!r}")
    for tier in tier_names(state):
        rows = state.get(tier)
        if not isinstance(rows, dict):
            continue  # `channels` is always named by `tier_names`; a missing one is caught below
        for name, row in rows.items():
            if not isinstance(row, dict):
                raise ValueError(
                    f"{tier}.{name} is {type(row).__name__}, not a channel row. A tier holds rows "
                    "and nothing else — a note or a comment beside them used to demote the whole "
                    "tier to unknown metadata, after which it was invisible to validate, diff and "
                    "render alike. Put free text in the snapshot's own `note`."
                )
    if not isinstance(state["sample_rate"], (int, float)) or state["sample_rate"] <= 0:
        raise ValueError(f"sample_rate must be a positive Hz, got {state['sample_rate']!r}")
    if "schema_version" in state and state["schema_version"] is not None:
        sv = state["schema_version"]
        if isinstance(sv, bool) or not isinstance(sv, int):
            raise ValueError(f"schema_version must be an int if present, got {sv!r}")
    # SCR-024: which project revision's facts this snapshot was taken under. Required in v3 —
    # without it a consumer joining `project.json`'s `channels[]` onto an old snapshot silently
    # relabels history (replace a driver and every past version reads as having had the new one).
    # `snapshot()` stamps it, so a hand-built state only has to say which revision it belongs to.
    rev = state.get("project_rev")
    if not isinstance(rev, int) or isinstance(rev, bool) or rev < 0:
        raise ValueError(
            f"project_rev must be a non-negative int (schema v{SCHEMA_VERSION}, SCR-024), got {rev!r}"
        )
    for tier in tier_names(state):
        required = ("hp", "lp", "gain_db", "ta_ms", "polarity") if tier == "channels" else ()
        rows = state.get(tier) if tier != "channels" else state["channels"]
        if tier == "channels" and (not isinstance(rows, dict) or not rows):
            raise ValueError("channels must be a non-empty object")
        if not isinstance(rows, dict):
            raise ValueError(f"{tier!r} must be an object of name→row, got {rows!r}")
        for ch_name, ch in rows.items():
            if not isinstance(ch, dict):
                raise ValueError(f"{tier}.{ch_name!r} must be an object, got {ch!r}")
            _validate_row(tier, ch_name, ch, required)
    return state


def samples_for(ms, sample_rate):
    """Derive DSP samples from canonical ms at the preset's native rate (never stored)."""
    return int(round(ms * sample_rate / 1000.0))


# ── store ─────────────────────────────────────────────────────────────────────
class PresetHistory:
    """Versioned snapshot history for one preset under a project-local root.

    The CODE lives in the skill; the DATA (snapshots) lives in the project — pass `root`
    (e.g. the project's `rew_analitic/state/`) so the same tooling serves any car/project.
    """

    def __init__(self, root, preset, project_dir=None):
        # No `makedirs` here: asking about a preset must not create it. A consumer UI resolving a
        # preset name from settings (or `contract.py` auditing a project) constructs this to find
        # out whether that preset exists at all -- and a stale name left in QSettings then silently
        # created a directory in the developer's real project data, which is how this was found.
        # `snapshot()` creates the directory when there is finally something to write into it.
        self.preset = preset
        self.dir = os.path.join(root, preset)
        # Where `project.json` lives, for the two things the ledger no longer holds itself:
        # `project_rev` to stamp (SCR-024) and channel identity to render (SCR-001). Defaults to
        # the parent of `root` because D1's canonical layout IS `<project>/state/<preset>/`; pass
        # it explicitly when the state root has been pointed somewhere else.
        self.project_dir = project_dir if project_dir is not None else os.path.dirname(
            os.path.abspath(root)
        )

    # -- versions --
    def versions(self):
        if not os.path.isdir(self.dir):
            return []  # never snapshotted -- "no versions", not a crash
        out = []
        for fn in os.listdir(self.dir):
            m = _VER_RE.match(fn[:-5]) if fn.endswith(".json") else None
            if m:
                out.append(fn[:-5])
        return sorted(out, key=lambda v: int(_VER_RE.match(v).group(1)))

    def _next_version(self):
        vs = self.versions()
        n = (int(_VER_RE.match(vs[-1]).group(1)) + 1) if vs else 1
        return f"v_{n:03d}"

    def _path(self, version):
        return os.path.join(self.dir, version + ".json")

    def _head_path(self):
        return os.path.join(self.dir, "HEAD")

    def head(self):
        hp = self._head_path()
        if os.path.exists(hp):
            with open(hp) as f:
                v = f.read().strip()
            if v in self.versions():
                return v
        vs = self.versions()
        return vs[-1] if vs else None

    def _set_head(self, version):
        with open(self._head_path(), "w") as f:
            f.write(version + "\n")

    # -- read/write --
    def load(self, version=None):
        version = version or self.head()
        if version is None:
            raise FileNotFoundError(f"no snapshots yet for preset {self.preset!r}")
        with open(self._path(version)) as f:
            return json.load(f)

    def snapshot(self, state, note=None, project_rev=None, project_dir=None):
        """Validate, assign the next version, write it, advance HEAD. Returns the version name.

        `project_rev` (SCR-024) is the revision of `project.json` in force when these values were
        banked. Read from the project's own file by default, since a snapshot is created NOW and
        the facts it should be read against are the ones true now — including on `revert()`, where
        old values are being re-applied to today's car. Pass it explicitly to override (a caller
        that already holds the number, or a migration restoring a historical one); pass
        `project_dir` to point at a project other than this history's own.
        """
        state = copy.deepcopy(state)
        state["preset"] = self.preset
        state["schema_version"] = SCHEMA_VERSION
        if project_rev is None:
            project_rev = _project_rev(project_dir if project_dir is not None else self.project_dir)
        state["project_rev"] = project_rev
        if note is not None:
            state["note"] = note
        validate(state)
        version = self._next_version()
        state["version"] = version
        state["created"] = datetime.datetime.now().isoformat(timespec="seconds")
        os.makedirs(self.dir, exist_ok=True)  # first snapshot is what creates the preset dir
        with open(self._path(version), "w") as f:
            json.dump(state, f, indent=2, sort_keys=True, ensure_ascii=False)
        self._set_head(version)
        return version

    def revert(self, version, note=None):
        """Forward-only revert: write a NEW snapshot copying `version`. History is never destroyed."""
        old = self.load(version)
        old.pop("version", None)
        old.pop("created", None)
        note = note or f"revert to {version}"
        return self.snapshot(old, note=note)

    # -- diff --
    def diff(self, va, vb):
        """Structured deltas va -> vb. Returns {'preset': {...}, 'channels': {ch: {field: [old,new]}}}."""
        a, b = self.load(va), self.load(vb)
        return diff_states(a, b)

    def render(self, version=None):
        """The settings sheet, with the Slot column joined back in from `project.json`.

        The slot letter is the single most operational thing on this sheet — it is what the Arbiter
        types into their DSP software — so moving identity out of the ledger (v3) must not cost the
        sheet that column. Read at render time, by `code`, exactly like any other consumer.
        """
        snap = self.load(version)
        return render_state(snap, channels=project_channels(self.project_dir),
                            current_target=current_target(self.project_dir, snap.get("preset", self.preset)),
                            processing_rate_hz=processing_rate(self.project_dir))


def _diff_scalar(a, b):
    return None if a == b else [a, b]


def diff_states(a, b):
    """Deltas between two state dicts (pure — no I/O). Only changed fields appear.

    One key per TIER present in either state (`channels` always, plus e.g. `virtual_channels`) —
    schema v2, 2026-07-29: a virtual-tier change used to vanish from the diff entirely (the split-
    artifact bug this module exists to prevent), since only `channels` was ever compared.
    """
    # `note`/`version`/`created` are per-snapshot labels, not comparable STATE — excluded on purpose.
    out = {"from": a.get("version"), "to": b.get("version"), "preset": {}}
    for k in ("sample_rate", "target", "roles", "provenance", "virtual_eq_ptr"):
        d = _diff_scalar(a.get(k), b.get(k))
        if d is not None:
            out["preset"][k] = d
    for tier in sorted(set(tier_names(a)) | set(tier_names(b))):
        a_rows, b_rows = a.get(tier) or {}, b.get(tier) or {}
        tier_out = {}
        for ch in sorted(set(a_rows) | set(b_rows)):
            if ch not in a_rows:
                tier_out[ch] = {"__added__": True}
                continue
            if ch not in b_rows:
                tier_out[ch] = {"__removed__": True}
                continue
            fields = {}
            for fld in CHANNEL_FIELDS:
                d = _diff_scalar(a_rows[ch].get(fld), b_rows[ch].get(fld))
                if d is not None:
                    fields[fld] = d
            if fields:
                tier_out[ch] = fields
        out[tier] = tier_out
    return out


# ── render (generated-only settings sheet) ───────────────────────────────────
def _fmt_filter(f):
    if f is None or f == "OFF":
        return "OFF"
    return f"{f['f']:g} {f.get('type', '?')} {f.get('slope', '?')}"


_STATUS_ICON = {"proposed": "🟡", "applied": "🟢", "measured": "📏"}


def _fmt_opt(v, spec="g"):
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        return format(v, spec)
    return "—" if v is None else str(v)


def render_state(state, channels=None, current_target=None, processing_rate_hz=None):
    """The human-applicable settings sheet, GENERATED from the source of truth.

    Never hand-edit this — edit the JSON and re-render. This is also the artifact the future
    `apply-change` gate hands the Arbiter to read at the PC-Tool screen (channel/param/old→new),
    which is what makes the compliant path the easiest path.

    `current_target` is the active target pointer (`current_target(project_dir, preset)`); when given
    it is what the header shows, because that is the curve the Arbiter EQs against now. The snapshot's
    own `target` — what this version was designed against — is the fallback and stays in the JSON.
    """
    # Samples derive from the DSP's PROCESSING rate (the profile) when the caller knows it; the
    # snapshot's own recorded rate is the fallback and is NAMED when they differ, because a silent
    # difference here is a wrong number in every row of the samples column.
    rate = processing_rate_hz if processing_rate_hz else state["sample_rate"]
    snap_rate = state["sample_rate"]
    roles = state.get("roles") or {}
    channels = channels or {}

    def slot_of(code):
        """The hardware slot for one row, from `project.json` (v3 identity, SCR-001)."""
        entry = channels.get(code) or {}
        value = entry.get("slot")
        value = value.get("value") if isinstance(value, dict) and "value" in value else value
        return value if value not in (None, "") else "—"

    lines = []
    lines.append(f"# DSP settings sheet — {state.get('preset', '?')} · {state.get('version', '(unsaved)')}")
    lines.append("")
    target_now = current_target if current_target is not None else state.get("target", "—")
    designed = state.get("target")
    target_line = f"target: {target_now}"
    if designed and current_target is not None and designed != current_target:
        target_line += f" (this version designed against {designed})"
    meta = [
        target_line,
        f"processing rate: {rate:g} Hz (samples derived; ms is canonical)"
        + (f" — the snapshot recorded {snap_rate:g}; samples follow the PROFILE rate"
           if processing_rate_hz and snap_rate != processing_rate_hz else ""),
        f"roles: artist={roles.get('artist', '—')} · producer={roles.get('producer', '—')} · critic={roles.get('critic', '—')}",
    ]
    prov = state.get("provenance") or {}
    if prov:
        # `provenance` is documented as an object ({"decision": ...}), but real ledgers in the
        # wild carry a plain sentence instead -- rendering used to crash outright on those
        # (`'str' object has no attribute 'get'`). Free-text is the lenient half of the schema,
        # so accept both shapes rather than refuse a snapshot that is otherwise perfectly valid.
        detail = prov.get("decision", prov.get("round", "—")) if isinstance(prov, dict) else prov
        meta.append(f"provenance: {detail}")
    if state.get("note"):
        meta.append(f"note: {state['note']}")
    if state.get("created"):
        meta.append(f"created: {state['created']}")
    lines += ["- " + m for m in meta]
    lines.append("")
    lines.append("| Channel | Slot | HP | LP | Pol | TA ms | TA smp | Gain dB | Status | EQ (out / virt) |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for ch_name, ch in state["channels"].items():
        # The sheet shows what is IN the ledger. `eq` (schema v2 band objects) is the bank the
        # Arbiter keys in; `eq_ptr` only points at an export file. The column read the pointer and
        # never the bank, so a ledger whose eight channels all carried 4-8 bands rendered `— / —`
        # (a live project, 2026-08-25) -- and "the Arbiter recognises their car in the sheet" cannot hold on
        # a sheet with no OUTPUT-EQ. Bands first; the pointer is the fallback, not the answer.
        ptr = ch.get("eq_ptr") or {}
        bands = eq_str(ch.get("eq"))
        out_s = " · ".join(bands) if bands else ptr.get("output", "—")
        eq_s = f"{out_s} / {ptr.get('virtual', '—')}"
        st = ch.get("status", "proposed")
        # `validate` accepts None in every required field (an `off: true` row has nothing to say);
        # `:g` on None raised TypeError and took the whole sheet down with it (a live project, 2026-08-25).
        # Render what is there, `—` for what is not, and say OFF where the row is switched off.
        ta = ch.get("ta_ms")
        ta_smp = samples_for(ta, rate) if isinstance(ta, (int, float)) and not isinstance(ta, bool) else "—"
        flags = "".join(f" {flag.upper()}" for flag in ("off", "mute") if ch.get(flag))
        lines.append(
            f"| {ch_name} | {slot_of(ch_name)} | {_fmt_filter(ch.get('hp'))} | {_fmt_filter(ch.get('lp'))} "
            f"| {ch.get('polarity') or '—'} | {_fmt_opt(ta)} | {ta_smp} | {_fmt_opt(ch.get('gain_db'))} "
            f"| {_STATUS_ICON.get(st, '?')} {st}{flags} | {eq_s} |"
        )
    for tier in tier_names(state):
        if tier == "channels":
            continue
        rows = state.get(tier) or {}
        if not rows:
            continue
        lines.append(f"### {tier}")
        lines.append("")
        lines.append("| Row | Slot | Gain dB | TA ms | TA smp | Pol | Phase° | Mute | EQ |")
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for name, row in rows.items():
            ta = row.get("ta_ms")
            ta_smp = samples_for(ta, rate) if isinstance(ta, (int, float)) else "—"
            bands = eq_str(row.get("eq"))
            lines.append(
                f"| {name} | {slot_of(name)} | {_fmt_opt(row.get('gain_db'))} "
                f"| {_fmt_opt(ta)} | {ta_smp} | {row.get('polarity', '—')} "
                f"| {_fmt_opt(row.get('phase_deg'))} | {'MUTE' if row.get('mute') else '—'} "
                f"| {' · '.join(bands) if bands else '—'} |"
            )
        lines.append("")
    verdicts = state.get("banked_ear_verdicts") or []
    if verdicts:
        lines += ["", "**Banked ear verdicts:**"] + [f"- {v}" for v in verdicts]
    lines.append("")
    return "\n".join(lines)


def render_diff(d):
    """Compact human view of diff_states() output — one section per tier that actually changed."""
    lines = [f"# diff {d.get('from')} → {d.get('to')}", ""]
    if d["preset"]:
        lines.append("**Preset-level:**")
        for k, (o, n) in d["preset"].items():
            lines.append(f"- {k}: {o!r} → {n!r}")
        lines.append("")
    any_tier = False
    for tier in sorted(k for k in d if k not in ("from", "to", "preset")):
        fields_by_ch = d[tier]
        if not fields_by_ch:
            continue
        any_tier = True
        lines.append(f"**{tier}:**")
        for ch, fields in fields_by_ch.items():
            if fields.get("__added__"):
                lines.append(f"- {ch}: ➕ added")
            elif fields.get("__removed__"):
                lines.append(f"- {ch}: ➖ removed")
            else:
                parts = [f"{fld} {o!r}→{n!r}" for fld, (o, n) in fields.items()]
                lines.append(f"- {ch}: " + " · ".join(parts))
        lines.append("")
    if not d["preset"] and not any_tier:
        lines.append("_(no changes)_")
    return "\n".join(lines) + "\n"


# ── multi-slot registry (issue #5: active-slot integrity) ─────────────────────
class Registry:
    """Which preset (slot) is ACTIVE in the physical DSP right now — the anti-cross-slot-anchoring
    pointer.

    A multi-preset processor (e.g. Helix Slot 1/2/3) invites a degrading model to anchor on the
    WRONG slot's gains: the real incident (issue #5) was tuning Slot 3 (SQ-Comp-Ref) while the top
    of a flat state table showed Slot 2 (ResoNix) numbers, so proposed HF filters were computed off
    a −8.0 dB baseline that belonged to a different slot. Each preset's snapshots already live
    physically isolated under `<root>/<preset>/` (PresetHistory); this registry adds the one missing
    thing — an explicit, machine-checked pointer to the live slot — and `render()` emits a LOUD
    banner so a top-down read hits the active slot first and can't drift to a neighbour's table.
    The apply gate (`apply.py propose`) reads this to REFUSE a change aimed at a non-active slot.
    """

    def __init__(self, root):
        # Read-only construction, same rule as `PresetHistory` above: `get_active()` on a project
        # with no `state/` yet answers "none", it doesn't materialise the tree.
        self.root = root

    def _path(self):
        return os.path.join(self.root, "registry.json")

    def list_presets(self):
        """Preset names that actually have a snapshot history under root (dirs holding v_NNN.json)."""
        out = []
        if os.path.isdir(self.root):
            for name in sorted(os.listdir(self.root)):
                d = os.path.join(self.root, name)
                if os.path.isdir(d) and any(
                        fn.endswith(".json") and _VER_RE.match(fn[:-5]) for fn in os.listdir(d)):
                    out.append(name)
        return out

    def load(self):
        p = self._path()
        if os.path.exists(p):
            with open(p) as f:
                return json.load(f)
        return {"active": None, "slots": {}}

    def _write(self, reg):
        reg["updated"] = datetime.datetime.now().isoformat(timespec="seconds")
        os.makedirs(self.root, exist_ok=True)
        with open(self._path(), "w") as f:
            json.dump(reg, f, indent=2, sort_keys=True, ensure_ascii=False)

    def get_active(self):
        return self.load().get("active")

    def set_active(self, preset):
        """Point the active slot at `preset`. Deterministic guard: it must already have a history."""
        presets = self.list_presets()
        if preset not in presets:
            raise ValueError(f"preset {preset!r} has no snapshot history under {self.root!r} "
                             f"(known: {presets or 'none'}) — seed it (history.snapshot) before "
                             f"making it the active slot")
        reg = self.load()
        reg["active"] = preset
        reg.setdefault("slots", {})
        self._write(reg)
        return preset

    def describe_slot(self, preset, label=None, note=None):
        """Attach an optional human label/desc to a slot (e.g. label='Slot 3', note='SQ-Comp-Ref')."""
        reg = self.load()
        entry = reg.setdefault("slots", {}).setdefault(preset, {})
        if label is not None:
            entry["label"] = label
        if note is not None:
            entry["note"] = note
        self._write(reg)
        return entry

    def render(self):
        return render_registry(self.root, self.load(), self.list_presets())


def render_registry(root, reg, presets):
    """LOUD active-slot banner + one isolated summary row per preset — the generated multi-slot
    `dsp-state-current` view. Generated-only (never hand-edited): a top-down read hits the ACTIVE
    banner first, so it cannot anchor on a neighbour slot's gains (issue #5)."""
    active = reg.get("active")
    slots = reg.get("slots") or {}
    lines = ["# DSP state — multi-slot registry", ""]
    if active:
        lbl = (slots.get(active) or {}).get("label")
        lines.append(f"> ⚠️ **ACTIVE SLOT IN THE DSP:** `{active}`" + (f" — {lbl}" if lbl else ""))
        lines.append("> Read and propose ONLY against this preset's section. The apply gate refuses "
                     "changes aimed at any other slot.")
    else:
        lines.append("> ⚠️ **NO ACTIVE SLOT SET** — run `state.py registry set-active <preset>` "
                     "before proposing any change.")
    lines.append("")
    if not presets:
        return "\n".join(lines + ["_(no presets have a snapshot history yet)_", ""])
    lines += ["| Slot (preset) | Active | HEAD | Target | Key gains (dB) |",
              "|---|---|---|---|---|"]
    for preset in presets:
        h = PresetHistory(root, preset)
        head = h.head()
        s = h.load(head) if head else {}
        chans = s.get("channels", {}) or {}
        gains = " · ".join(f"{c}={chans[c].get('gain_db')}" for c in list(chans)[:4]) if chans else "—"
        lbl = (slots.get(preset) or {}).get("label")
        name = preset + (f" — {lbl}" if lbl else "")
        mark = "✅" if preset == active else ""
        tgt = current_target(h.project_dir, preset) or s.get("target") or "—"
        lines.append(f"| {name} | {mark} | {head or '—'} | {tgt} | {gains} |")
    lines.append("")
    return "\n".join(lines)


# ── CLI ───────────────────────────────────────────────────────────────────────
def _main(argv=None):
    p = argparse.ArgumentParser(description="Versioned hard-params DSP state")
    p.add_argument("--root", default=os.environ.get("AUTOSOUND_STATE_ROOT", "state"),
                   help="directory holding <preset>/ snapshots (project-local; env AUTOSOUND_STATE_ROOT)")
    sub = p.add_subparsers(dest="cmd")
    for name in ("log", "render", "revert"):
        sp = sub.add_parser(name)
        sp.add_argument("preset")
        if name in ("render", "revert"):
            sp.add_argument("version", nargs="?", default=None)
    sp = sub.add_parser("diff")
    sp.add_argument("preset")
    sp.add_argument("va")
    sp.add_argument("vb")
    rp = sub.add_parser("registry", help="multi-slot active-slot pointer (issue #5)")
    rp.add_argument("action", choices=["show", "set-active", "render", "describe"])
    rp.add_argument("preset", nargs="?", default=None)
    rp.add_argument("--label", default=None)
    rp.add_argument("--note", default=None)
    sub.add_parser("selftest")
    args = p.parse_args(argv)

    if args.cmd == "selftest" or args.cmd is None:
        return _selftest()
    if args.cmd == "registry":
        reg = Registry(args.root)
        if args.action == "set-active":
            print("active →", reg.set_active(args.preset))
        elif args.action == "describe":
            print(reg.describe_slot(args.preset, label=args.label, note=args.note))
        elif args.action == "render":
            print(reg.render())
        else:  # show
            print(json.dumps(reg.load(), indent=2, ensure_ascii=False))
        return 0
    h = PresetHistory(args.root, args.preset)
    if args.cmd == "log":
        for v in h.versions():
            s = h.load(v)
            head = " (HEAD)" if v == h.head() else ""
            print(f"{v}{head}  {s.get('created', '')}  {s.get('note', '')}")
    elif args.cmd == "render":
        print(h.render(args.version))
    elif args.cmd == "diff":
        print(render_diff(h.diff(args.va, args.vb)))
    elif args.cmd == "revert":
        print("wrote", h.revert(args.version))


# ── self-test ─────────────────────────────────────────────────────────────────
def _sample_state():
    """A minimal Passat-shaped state (grounded in dsp-state-current clean-slate).

    Carries `preset` itself (normally injected by `snapshot()`) so `validate()` can also be called
    directly on this fixture, as several selftest cases below do -- without it every direct
    `validate()` call raised on the missing key regardless of what it was actually trying to
    exercise (a latent gap in the pre-schema-v2 selftest).

    No `slot`/`descr`/`role`/`order`/`hidden` on any row: schema v3 keeps identity in
    `project.json` (SCR-001). The rows here are pure tuning state, which is the whole point of the
    split -- what a snapshot captures is what could have been different last week."""
    return {
        "preset": "SQ_Jazzi",
        "sample_rate": 96000,
        "project_rev": 1,
        "target": "Jazzi",
        "roles": {"artist": "Gemini", "producer": "Claude", "critic": None},
        "provenance": {"decision": "clean-slate by-ear 2026-06-18"},
        "banked_ear_verdicts": [],
        "virtual_eq_ptr": None,
        "channels": {
            "sub":  {"hp": {"f": 20, "type": "BE", "slope": 12},
                     "lp": {"f": 45, "type": "BW", "slope": 12}, "gain_db": -6.0,
                     "ta_ms": 5.0, "polarity": "NORM", "eq_ptr": {}, "status": "applied"},
            "w-L":  {"hp": {"f": 70, "type": "BW", "slope": 12},
                     "lp": {"f": 270, "type": "BW", "slope": 12}, "gain_db": -7.8,
                     "ta_ms": 5.38, "polarity": "NORM", "eq_ptr": {}, "status": "applied"},
            "tw-R": {"mute": False, "off": False,
                     "hp": {"f": 5000, "type": "BE", "slope": 12},
                     "lp": "OFF", "gain_db": -6.0, "ta_ms": 4.09, "polarity": "NORM",
                     "eq_ptr": {}, "status": "applied"},
        },
        # a second tier (Helix-shaped: no crossover, phase/mute instead) -- present in every
        # fixture so validate/diff/apply are exercised tier-aware by default, not as a bolt-on.
        "virtual_channels": {
            "VFL": {"gain_db": 0.0, "ta_ms": 0.0, "polarity": "NORM",
                    "eq": [{"type": "LSH", "f": 150, "gain_db": 2.5, "q": 0.71}]},
            "VFR": {"gain_db": 0.0, "ta_ms": 0.0, "polarity": "NORM"},
        },
    }


def _selftest():
    import tempfile
    root = tempfile.mkdtemp(prefix="autosound_state_")
    h = PresetHistory(root, "SQ_Jazzi")

    v1 = h.snapshot(_sample_state(), note="baseline clean-slate")
    assert v1 == "v_001", v1
    assert h.head() == "v_001"
    assert h.load("v_001")["schema_version"] == SCHEMA_VERSION, "snapshot() must stamp schema_version"

    # ms is canonical; samples derive from 96 kHz (5.38 ms → 516 smp).
    assert samples_for(5.38, 96000) == 516, samples_for(5.38, 96000)
    # the SAME ms on a 48 kHz DSP is half the samples — the hazard the design guards.
    assert samples_for(5.38, 48000) == 258

    # change three things: sub polarity, w-L gain, w-L TA -- plus a VIRTUAL-tier change (VFL gain).
    s2 = h.load()
    s2["channels"]["sub"]["polarity"] = "INV"
    s2["channels"]["w-L"]["gain_db"] = -7.5
    s2["channels"]["w-L"]["ta_ms"] = 5.45
    s2["virtual_channels"]["VFL"]["gain_db"] = -1.0
    v2 = h.snapshot(s2, note="sub INV test + w-L trim + VFL gain")
    assert v2 == "v_002" and h.head() == "v_002"

    d = h.diff("v_001", "v_002")
    assert d["channels"]["sub"]["polarity"] == ["NORM", "INV"], d
    assert d["channels"]["w-L"]["gain_db"] == [-7.8, -7.5], d
    assert d["channels"]["w-L"]["ta_ms"] == [5.38, 5.45], d
    assert "tw-R" not in d["channels"], "unchanged channel must not appear in the diff"
    # schema v2: a virtual-tier change must show up in the diff too -- it used to vanish entirely
    # since diff_states only ever compared `channels` (the split-artifact bug this file exists to
    # prevent, now happening to a whole tier instead of one field).
    assert d["virtual_channels"]["VFL"]["gain_db"] == [0.0, -1.0], d
    assert "VFR" not in d["virtual_channels"], "unchanged virtual row must not appear in the diff"
    assert d["preset"] == {}, d

    # render is generated + carries derived samples and the status icon.
    r = h.render("v_001")
    assert "516" in r and "5.38" in r, r          # derived samples present
    assert "🟢 applied" in r, r
    assert "samples derived; ms is canonical" in r
    # The header shows the CURRENT target pointer (process/process-state.json targets), not the
    # snapshot's own historical `target` -- a live project rendered `—` after `process target` set
    # the curve, because the sheet read the snapshot and the pointer lived elsewhere (2026-08-25).
    # h.project_dir is the parent of `root`; put a process dir there with a moved pointer.
    _proc = os.path.join(h.project_dir, "process")
    os.makedirs(_proc, exist_ok=True)
    with open(os.path.join(_proc, "process-state.json"), "w", encoding="utf-8") as _fh:
        json.dump({"targets": {"SQ_Jazzi": "Resonalyze"}}, _fh)
    assert current_target(h.project_dir, "SQ_Jazzi") == "Resonalyze"
    assert current_target(h.project_dir, "Nope") is None and current_target("/no/such", "SQ_Jazzi") is None
    r_now = h.render("v_001")
    assert "target: Resonalyze" in r_now, r_now
    # the snapshot's own target (Jazzi) is not lost -- it is named as what this version was designed against
    assert "designed against Jazzi" in r_now, r_now
    # registry render shows the pointer too
    reg_txt = Registry(root).render()
    assert "Resonalyze" in reg_txt, reg_txt
    os.remove(os.path.join(_proc, "process-state.json"))
    # with no pointer, the header falls back to the snapshot's own target
    assert "target: Jazzi" in h.render("v_001")
    # An `off: true` row with null ta_ms/gain_db passes validate, so render must take it too --
    # it used to raise TypeError on `{None:g}` (a live project, 2026-08-25). And the EQ column must show the
    # ledger's own `eq` bands, not only an `eq_ptr` pointer.
    offrow = _sample_state()
    offrow["channels"]["r-L"] = {"hp": None, "lp": None, "gain_db": None, "ta_ms": None,
                                 "polarity": None, "off": True, "status": "applied"}
    offrow["channels"]["w-L"]["eq"] = [{"type": "PK", "f": 160, "gain_db": -4.0, "q": 3.0}]
    validate(offrow)
    r_off = render_state(offrow)
    off_line = next(l for l in r_off.splitlines() if l.startswith("| r-L "))
    assert "OFF" in off_line and "| — | — | — |" in off_line, off_line
    w_line = next(l for l in r_off.splitlines() if l.startswith("| w-L "))
    assert "PK 160 -4 Q3" in w_line, w_line

    # revert is forward-only: v_003 == v_001 content, history intact.
    v3 = h.revert("v_001", note="back to baseline")
    assert v3 == "v_003" and h.head() == "v_003"
    assert h.load("v_003")["channels"]["sub"]["polarity"] == "NORM"
    assert h.versions() == ["v_001", "v_002", "v_003"], h.versions()

    # validation refuses garbage (the gate-in-embryo).
    bad = _sample_state()
    bad["channels"]["w-L"]["polarity"] = "sideways"
    try:
        h.snapshot(bad)
        raise AssertionError("snapshot accepted an invalid polarity")
    except ValueError:
        pass

    # ── schema v3: identity is NOT in the ledger (SCR-001) ──
    reloaded = h.load("v_001")
    assert reloaded["channels"]["tw-R"]["mute"] is False, reloaded["channels"]["tw-R"]
    assert not any(
        f in row
        for row in reloaded["channels"].values()
        for f in MOVED_TO_PROJECT_JSON
    ), reloaded["channels"]

    # a snapshot still carrying identity is REFUSED, not silently stripped: dropping it on write
    # would lose the only copy of a `descr` nobody had put into project.json yet.
    for moved_field, moved_value in (("slot", "K"), ("descr", "Sub"), ("role", "sub"),
                                     ("order", 0), ("hidden", True), ("tag_value", "3/4")):
        stale = _sample_state()
        stale["channels"]["sub"][moved_field] = moved_value
        try:
            validate(stale)
            raise AssertionError(f"validate accepted ledger-side {moved_field!r}")
        except ValueError as exc:
            assert "moved out of the ledger" in str(exc), exc

    # SCR-024: a snapshot says which project revision its values were dialled against, and
    # `project_dir=` reads that number from the project's own file rather than being told twice.
    # This history has no project.json beside it, so the stamp is 0 -- "no facts recorded yet",
    # not the fixture's own value: what a snapshot records is the revision in force at write time.
    assert reloaded["project_rev"] == 0, reloaded
    proj_root = tempfile.mkdtemp(prefix="autosound_state_proj_")
    with open(os.path.join(proj_root, "project.json"), "w", encoding="utf-8") as f:
        json.dump({"schema_version": SCHEMA_VERSION, "project_rev": 7,
                   "channels": [{"code": "sub", "slot": "K", "descr": "Subwoofer"},
                                {"code": "VFL", "slot": "A"}]}, f)
    hp2 = PresetHistory(os.path.join(proj_root, "state"), "SQ_Jazzi", project_dir=proj_root)
    vp = hp2.snapshot(_sample_state(), note="stamped from the project file")
    assert hp2.load(vp)["project_rev"] == 7, hp2.load(vp)

    # the settings sheet keeps its Slot column -- joined back in from project.json at render time.
    # It is what the Arbiter types into the DSP, so the v3 move must not cost the sheet that column.
    sheet = hp2.render(vp)
    assert "| sub | K |" in sheet, sheet
    assert "| VFL | A |" in sheet, sheet
    assert "| w-L | — |" in sheet, sheet  # no project entry yet -> honest dash, not a crash

    # SCR-039: the snapshot above is keyed `sub`/`VFL` forever. Rename `sub` in project.json and
    # the sheet must still find its slot -- a snapshot is immutable, so its key is the channel's
    # id, and identity resolves through that id and through the name it used to have.
    with open(os.path.join(proj_root, "project.json"), "w", encoding="utf-8") as f:
        json.dump({"schema_version": SCHEMA_VERSION, "project_rev": 8,
                   "channels": [{"code": "sw", "id": "sub", "previous_names": ["sub"],
                                 "slot": "K", "descr": "Subwoofer"},
                                {"code": "VFL", "slot": "A"}]}, f)
    renamed = hp2.render(vp)
    assert "| sub | K |" in renamed, renamed
    identity = project_channels(proj_root)
    assert identity["sub"] is identity["sw"], "id, current name and old name are one channel"

    no_rev = _sample_state()
    del no_rev["project_rev"]
    try:
        validate(no_rev)
        raise AssertionError("validate accepted a snapshot with no project_rev")
    except ValueError as exc:
        assert "project_rev" in str(exc), exc

    bad_mute = _sample_state()
    bad_mute["channels"]["sub"]["mute"] = "yes"  # must be a bool
    try:
        validate(bad_mute)
        raise AssertionError("validate accepted a non-bool mute")
    except ValueError:
        pass

    # `bool` subclasses `int`, so a bare isinstance(x, int) would let `true` through and sort as 1.
    bool_order = _sample_state()
    bool_order["channels"]["sub"]["order"] = True
    try:
        validate(bool_order)
        raise AssertionError("validate accepted a bool as order")
    except ValueError:
        pass

    # structured `eq` bands + `phase_deg` are tuning state, so they stay on the row; a snapshot
    # must round-trip them, and the gate must not refuse them as unknown. (`role` used to be
    # asserted here too -- it is identity now, and lives in project.json.)
    with_eq = _sample_state()
    with_eq["channels"]["w-L"]["eq"] = [
        {"type": "PK", "f": 1000, "gain_db": -9, "q": 2},
        {"type": "LSH", "f": 150, "gain_db": 2.5, "q": 0.71},
    ]
    with_eq["channels"]["w-L"]["phase_deg"] = 90
    vq = h.snapshot(with_eq, note="structured eq")
    back = h.load(vq)["channels"]["w-L"]
    assert back["eq"] == [
        {"type": "PK", "f": 1000, "gain_db": -9, "q": 2},
        {"type": "LSH", "f": 150, "gain_db": 2.5, "q": 0.71},
    ], back
    assert back["phase_deg"] == 90, back

    # an unknown EQ band type is a deterministic refusal, same discipline as bad polarity.
    bad_eq = _sample_state()
    bad_eq["channels"]["w-L"]["eq"] = [{"type": "XX", "f": 1000}]
    try:
        validate(bad_eq)
        raise AssertionError("validate accepted an unknown EQ band type")
    except ValueError:
        pass

    # other tiers have NO required fields (only `channels` does) -- a virtual row carrying just a
    # gain is legal, the lenient half of the tier-aware split. Lenient about which TUNING fields
    # are present; not lenient about identity, which is v3's one hard line and applies to every
    # tier (a virtual slot's `descr` belongs in project.json exactly like a physical one's).
    lenient = _sample_state()
    lenient["virtual_channels"]["VFR"] = {"gain_db": -1.0}
    validate(lenient)  # must not raise

    # EQ display helpers: structured <-> string, including the LS/HS shorthand alias the two
    # hand-authored v1 ledgers actually use (canonical types are `EQ_TYPES`; migrate.py relies
    # on this alias to upgrade them without hand-transcription).
    assert eq_band_from_str("LS 150 +2.5 Q0.71") == {
        "type": "LSH", "f": 150.0, "gain_db": 2.5, "q": 0.71}, eq_band_from_str("LS 150 +2.5 Q0.71")
    assert eq_band_str({"type": "PK", "f": 1000, "gain_db": -9, "q": 2}) == "PK 1000 -9 Q2"
    assert eq_str([{"type": "PK", "f": 1000, "gain_db": -9, "q": 2}]) == ["PK 1000 -9 Q2"]

    # the generated settings sheet gets a section for every non-`channels` tier that has rows.
    r_full = h.render(vq)
    assert "### virtual_channels" in r_full, r_full
    assert "VFL" in r_full and "LSH 150" in r_full, r_full

    # a real ledger in the wild carries `provenance` as a plain sentence, not the documented
    # {"decision": ...} object -- render used to crash on that ('str' has no attribute 'get').
    prov_str = _sample_state()
    prov_str["provenance"] = "attested-latest 2026-07-23, rebuilt from settled config"
    assert "attested-latest" in render_state(prov_str), "string provenance must render, not crash"

    # ── multi-slot registry (issue #5): active-slot pointer + LOUD banner ──
    h2 = PresetHistory(root, "ResoNix")
    h2.snapshot(_sample_state(), note="resonix baseline")     # a second slot to disambiguate
    reg = Registry(root)
    assert set(reg.list_presets()) == {"SQ_Jazzi", "ResoNix"}, reg.list_presets()
    try:
        reg.set_active("SQ_Comp_Ref")                          # no history → deterministic refusal
        raise AssertionError("set_active accepted a preset with no history")
    except ValueError:
        pass
    reg.set_active("SQ_Jazzi")
    assert reg.get_active() == "SQ_Jazzi"
    banner = reg.render()
    assert "ACTIVE SLOT IN THE DSP:** `SQ_Jazzi`" in banner, banner
    assert "ResoNix" in banner, "every slot must still be listed (isolated rows)"
    active_row = [ln for ln in banner.splitlines() if ln.startswith("| SQ_Jazzi")][0]
    assert "✅" in active_row, active_row

    # -- one stray value must not hide a whole tier (2026-08-12) --------------------------------
    # `tier_names` required a dict OF DICTS, so a single non-dict value demoted the key to unknown
    # metadata -- and `validate` never looks at unknown keys, so the tier passed and then vanished
    # from validate, diff and render at once. That is the split-artifact bug this module exists to
    # prevent, re-armed by one line.
    strayed = {
        "preset": "SQ", "sample_rate": 96000, "project_rev": 1, "schema_version": SCHEMA_VERSION,
        "channels": {"w-L": {"gain_db": -7.8, "polarity": "NORM"}},
        "virtual_channels": {"VFL": {"gain_db": 0.0}, "comment": "temp note"},
    }
    assert "virtual_channels" in tier_names(strayed), tier_names(strayed)
    try:
        validate(strayed)
        raise AssertionError("validate accepted a note sitting where a channel row goes")
    except ValueError as exc:
        assert "comment" in str(exc), exc

    print(f"selftest OK — 3 snapshots, diff caught the channels+virtual_channels changes (schema "
          f"v2 tier-aware), 5.38 ms → 516 smp @96k (258 @48k), revert forward-only (v_001→v_003), "
          f"validation rejected bad polarity + an unknown EQ type, structured EQ round-tripped "
          f"(incl. LS→LSH alias), render emitted a virtual_channels section; registry: 2 slots "
          f"isolated, active=SQ_Jazzi loud-bannered, set-active refused a history-less slot; v3: identity refused on every tier, project_rev stamped from project.json (0 without one), settings sheet joined its Slot column back in. "
          f"root={root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
