"""Versioned hard-params DSP state — the anti-drift anchor AND the experimentation engine.

The single source of truth is one JSON per snapshot (`v_NNN.json`) under `<root>/<preset>/`.
A human-readable Markdown settings sheet is GENERATED from that JSON (`render`); it is never
hand-edited. Editing a rendered view instead of the source is the split-artifact trap
(gains-lived-in-a-screenshot while EQ-lived-in-.req → a careful reader mis-concluded "no gain
change") that this module exists to kill: one file per snapshot holds crossovers + gains + TA +
polarity + EQ pointers together, so nobody ever reads a partial picture.

Why versioned: the same file that stops drift (write-after-every-change, read-before-edit) is what
makes weird ideas cheap to try — a snapshot is a diff/A-B/revert away, so experimentation costs
one command. Stability and freedom are the same mechanism, not opposites.

Layout
    <root>/<preset>/v_001.json, v_002.json, ...   immutable snapshots
    <root>/<preset>/HEAD                           text file: the current version name

Design invariants
    * ms is the CANONICAL delay unit; samples are DERIVED from the preset's sample_rate at render
      time and never stored. Entering 96 kHz samples into a 48 kHz DSP doubles the physical delay
      and ruins alignment — so the file commits to ms, and samples are a view.
    * status lifecycle (AD-1): proposed -> applied -> measured. The file is the source of truth for
      INTENT + ATTESTED-APPLIED, NOT a guaranteed device mirror; device-truth is the latest
      measurement. The design claims nothing more.
    * snapshot() VALIDATES before writing and refuses on malformed state — a deterministic gate in
      embryo (a confabulated/garbage state can't be silently banked).
    * revert() is forward-only: it writes a NEW snapshot copying an old one, never destroys history.

Schema v2 (2026-07-29, autosound-tcc sync): the ledger is TIER-AWARE, not `channels`-only. A tier
is any top-level key holding a dict of row-dicts -- `channels` (the required physical-outputs
tier, unchanged key name) plus any other profile-declared tier a project's DSP has (e.g.
`virtual_channels`). `validate`/`diff_states`/`apply.propose` all walk every tier present; only
`channels` carries the strict required-field list (hp/lp/gain_db/ta_ms/polarity) since it is the
one tier every DSP profile has. A NEW tier must exist as a (possibly empty) top-level key before a
delta can address it by name -- intake seeds every profile-declared tier, even empty, at the first
snapshot; see `tier_names()`. `eq` bands are now STRUCTURED OBJECTS
(`{"type": "PK", "f": 1000, "gain_db": -9, "q": 2, "bypass": false}`), not strings -- the old
inline string form is display-only now, generated by `eq_str()`. `schema_version` is stamped on
every snapshot going forward.
"""

import argparse
import copy
import datetime
import json
import os
import re

# ── schema ──────────────────────────────────────────────────────────────────
SCHEMA_VERSION = 2
POLARITIES = ("NORM", "INV")
STATUSES = ("proposed", "applied", "measured")
EQ_TYPES = ("PK", "LSH", "HSH", "APF1", "APF2")
CHANNEL_FIELDS = (
    "slot", "descr", "role", "order", "tag", "tag_value", "mute", "off", "hidden",
    "hp", "lp", "gain_db", "ta_ms", "polarity", "phase_deg", "eq", "eq_ptr", "status",
)
# `slot` was `helix_ch` before this schema pass (2026-07-29, autosound-tcc SCR "submodule task
# A6") -- renamed vendor-neutral since a MUSWAY/other DSP has no "helix channel" concept, just a
# hardware slot letter/number. `descr`/`role`/`order`/`tag`/`tag_value`/`mute`/`off`/`hidden` are
# new, optional annotations a consumer UI (autosound-tcc) renders -- see
# autosound-tcc/src/autosound_tcc/state/dsp_state.py's `GroupRow` for exactly how each is read.
#
# `eq` (a list of structured band objects, schema v2) coexists with the older `eq_ptr` (a pointer
# to a `.req` export file) rather than replacing it: they answer different questions -- `eq_ptr`
# says where the authoritative export lives, `eq` carries the bands themselves so a reader needs
# no second file. Listing `eq` here only makes it a legal field to carry/merge/diff; DERIVING
# bands from measurement data is separate, unbuilt work.
TOP_REQUIRED = ("preset", "sample_rate", "channels")
# Top-level keys that hold project/preset METADATA, not a tier of rows, even though some are
# dict-valued (`roles` is {role: name}, `provenance` may be a dict OR a free sentence) -- every
# OTHER top-level key whose value is a dict is a tier (`tier_names()`), the same convention
# `autosound-tcc`'s `ProjectView.from_dict` already reads by (physical_outputs -> `channels`, any
# other profile group id -> a same-named top-level key).
_NON_TIER_KEYS = {
    "preset", "version", "created", "schema_version", "sample_rate", "target", "roles",
    "provenance", "banked_ear_verdicts", "virtual_eq_ptr", "note", "features", "slot_label",
    "save",
}
_VER_RE = re.compile(r"^v_(\d{3,})$")
_EQ_GAIN_RE = re.compile(r"^[+-][\d.]+$")
_EQ_Q_RE = re.compile(r"^[Qq]([\d.]+)$")
_EQ_NUM_RE = re.compile(r"^[\d.]+$")
_EQ_TYPE_ALIASES = {"LS": "LSH", "HS": "HSH"}  # shorthand seen in hand-authored v1 ledgers


def tier_names(state):
    """Every tier key present in `state`: `channels` (always, even if absent -- callers checking
    membership still get the right answer from `validate`) plus any other top-level key whose
    value is a dict-of-dicts (e.g. `virtual_channels`). An EMPTY tier dict still counts -- that is
    what lets intake seed a tier before the first row exists in it (see the schema-v2 note above)."""
    out = ["channels"]
    for k, v in state.items():
        if k in _NON_TIER_KEYS or k == "channels":
            continue
        if isinstance(v, dict) and all(isinstance(row, dict) for row in v.values()):
            out.append(k)
    return out


def eq_band_from_str(raw):
    """Parse one legacy inline EQ band string (e.g. `"PK 1000 -9 Q2"`) into a v2 band object.

    Migration-only (`migrate_v2.py`) -- the band OBJECT is canonical going forward; this exists so
    the two hand-authored v1 ledgers upgrade without hand-transcription. Tolerates the `LS`/`HS`
    shorthand actually used in those files (canonical types are `EQ_TYPES`).
    """
    tokens = raw.split()
    if not tokens:
        raise ValueError("empty EQ band string")
    band_type = _EQ_TYPE_ALIASES.get(tokens[0], tokens[0])
    freq_hz = gain_db = q = None
    for tok in tokens[1:]:
        if freq_hz is None and _EQ_NUM_RE.match(tok):
            freq_hz = float(tok)
        elif _EQ_GAIN_RE.match(tok):
            gain_db = float(tok)
        elif _EQ_Q_RE.match(tok):
            q = float(_EQ_Q_RE.match(tok).group(1))
    if freq_hz is None:
        raise ValueError(f"could not parse a frequency from EQ band {raw!r}")
    band = {"type": band_type, "f": freq_hz}
    if gain_db is not None:
        band["gain_db"] = gain_db
    if q is not None:
        band["q"] = q
    return band


def eq_band_str(band):
    """One band object rendered as the old inline string (e.g. `"PK 1000 -9 Q2"`) -- display-only
    now (chat output, the settings sheet, the Helix-export path); the band object is canonical."""
    parts = [band["type"], f"{band['f']:g}"]
    if band.get("gain_db") is not None:
        parts.append(f"{band['gain_db']:+g}")
    if band.get("q") is not None:
        parts.append(f"Q{band['q']:g}")
    if band.get("bypass"):
        parts.append("(bypass)")
    return " ".join(parts)


def eq_str(bands):
    """A whole `eq` list rendered as display strings, oldest-format-compatible, in order."""
    return [eq_band_str(b) for b in (bands or [])]


def _validate_filter(name, ch_name, f):
    """A crossover leg is null / "OFF" (disabled) or {f, type, slope}."""
    if f is None or f == "OFF":
        return
    if not isinstance(f, dict) or "f" not in f:
        raise ValueError(f"{ch_name}.{name}: expected null/'OFF' or {{f,type,slope}}, got {f!r}")
    if not isinstance(f["f"], (int, float)) or f["f"] <= 0:
        raise ValueError(f"{ch_name}.{name}.f must be a positive Hz, got {f.get('f')!r}")


def _validate_eq(tier, ch_name, eq):
    if not isinstance(eq, list):
        raise ValueError(f"{tier}.{ch_name}.eq must be a list of band objects, got {eq!r}")
    seen_i = set()
    for idx, band in enumerate(eq):
        if not isinstance(band, dict):
            raise ValueError(f"{tier}.{ch_name}.eq[{idx}] must be an object, got {band!r}")
        if band.get("type") not in EQ_TYPES:
            raise ValueError(f"{tier}.{ch_name}.eq[{idx}].type must be one of {EQ_TYPES}, "
                             f"got {band.get('type')!r}")
        f = band.get("f")
        if not isinstance(f, (int, float)) or isinstance(f, bool) or f <= 0:
            raise ValueError(f"{tier}.{ch_name}.eq[{idx}].f must be a positive Hz, got {f!r}")
        for numf in ("gain_db", "q"):
            if numf in band and band[numf] is not None and not isinstance(band[numf], (int, float)):
                raise ValueError(f"{tier}.{ch_name}.eq[{idx}].{numf} must be a number if present, "
                                 f"got {band[numf]!r}")
        if "bypass" in band and band["bypass"] is not None and not isinstance(band["bypass"], bool):
            raise ValueError(f"{tier}.{ch_name}.eq[{idx}].bypass must be a bool if present, "
                             f"got {band['bypass']!r}")
        if "i" in band and band["i"] is not None:
            if isinstance(band["i"], bool) or not isinstance(band["i"], int):
                raise ValueError(f"{tier}.{ch_name}.eq[{idx}].i must be an int if present, "
                                 f"got {band['i']!r}")
            if band["i"] in seen_i:
                raise ValueError(f"{tier}.{ch_name}.eq: duplicate band index i={band['i']!r}")
            seen_i.add(band["i"])


def _validate_row(tier, ch_name, ch, required):
    """One tier row's fields, generic across tiers. `required` (only non-empty for `channels`,
    the one tier every DSP profile has) lists fields that must be KEYS on the row; everything else
    is type-checked only when present -- a virtual-channel row with no `hp`/`lp` at all is not an
    error, a `hp` that IS there but malformed is."""
    missing = [f for f in required if f not in ch]
    if missing:
        raise ValueError(f"{tier}.{ch_name!r} missing {missing}")
    if "hp" in ch:
        _validate_filter("hp", ch_name, ch["hp"])
    if "lp" in ch:
        _validate_filter("lp", ch_name, ch["lp"])
    if "gain_db" in ch and ch["gain_db"] is not None and not isinstance(ch["gain_db"], (int, float)):
        raise ValueError(f"{tier}.{ch_name}.gain_db must be a number, got {ch['gain_db']!r}")
    if "ta_ms" in ch and ch["ta_ms"] is not None and not isinstance(ch["ta_ms"], (int, float)):
        raise ValueError(f"{tier}.{ch_name}.ta_ms must be a number (ms is canonical), got {ch['ta_ms']!r}")
    if "polarity" in ch and ch["polarity"] is not None and ch["polarity"] not in POLARITIES:
        raise ValueError(f"{tier}.{ch_name}.polarity must be one of {POLARITIES}, got {ch['polarity']!r}")
    st = ch.get("status")
    if st is not None and st not in STATUSES:
        raise ValueError(f"{tier}.{ch_name}.status must be one of {STATUSES}, got {st!r}")
    # `bool` is a subclass of `int` in Python, so an explicit bool reject is needed -- an
    # `"order": true` would otherwise sail through and sort as 1.
    if "order" in ch and ch["order"] is not None:
        if isinstance(ch["order"], bool) or not isinstance(ch["order"], int):
            raise ValueError(f"{tier}.{ch_name}.order must be an int if present, got {ch['order']!r}")
    for flag in ("mute", "off", "hidden"):
        if flag in ch and ch[flag] is not None and not isinstance(ch[flag], bool):
            raise ValueError(f"{tier}.{ch_name}.{flag} must be a bool if present, got {ch[flag]!r}")
    if "eq" in ch and ch["eq"] is not None:
        _validate_eq(tier, ch_name, ch["eq"])


def validate(state):
    """Raise ValueError on malformed state; return the state unchanged if OK.

    Walks every TIER (`tier_names`), not just `channels` -- schema v2 (2026-07-29). Only `channels`
    (the physical-outputs tier every DSP profile has) carries the strict required-field list;
    other tiers (e.g. `virtual_channels`) are validated leniently, same "strict on silent/expensive
    errors, lenient on the rest" split as before. `note`/`provenance` stay unchecked free-text.
    """
    for k in TOP_REQUIRED:
        if k not in state:
            raise ValueError(f"state missing required key {k!r}")
    if not isinstance(state["sample_rate"], (int, float)) or state["sample_rate"] <= 0:
        raise ValueError(f"sample_rate must be a positive Hz, got {state['sample_rate']!r}")
    if "schema_version" in state and state["schema_version"] is not None:
        sv = state["schema_version"]
        if isinstance(sv, bool) or not isinstance(sv, int):
            raise ValueError(f"schema_version must be an int if present, got {sv!r}")
    for tier in tier_names(state):
        required = ("hp", "lp", "gain_db", "ta_ms", "polarity") if tier == "channels" else ()
        rows = state.get(tier) if tier != "channels" else state["channels"]
        if tier == "channels" and (not isinstance(rows, dict) or not rows):
            raise ValueError("channels must be a non-empty object")
        if not isinstance(rows, dict):
            raise ValueError(f"{tier!r} must be an object of name→row, got {rows!r}")
        for ch_name, ch in rows.items():
            if not isinstance(ch, dict):
                raise ValueError(f"{tier}.{ch_name!r} must be an object, got {ch!r}")
            _validate_row(tier, ch_name, ch, required)
    return state


def samples_for(ms, sample_rate):
    """Derive DSP samples from canonical ms at the preset's native rate (never stored)."""
    return int(round(ms * sample_rate / 1000.0))


# ── store ─────────────────────────────────────────────────────────────────────
class PresetHistory:
    """Versioned snapshot history for one preset under a project-local root.

    The CODE lives in the skill; the DATA (snapshots) lives in the project — pass `root`
    (e.g. the project's `rew_analitic/state/`) so the same tooling serves any car/project.
    """

    def __init__(self, root, preset):
        # No `makedirs` here: asking about a preset must not create it. A consumer UI resolving a
        # preset name from settings (or `contract.py` auditing a project) constructs this to find
        # out whether that preset exists at all -- and a stale name left in QSettings then silently
        # created a directory in the developer's real project data, which is how this was found.
        # `snapshot()` creates the directory when there is finally something to write into it.
        self.preset = preset
        self.dir = os.path.join(root, preset)

    # -- versions --
    def versions(self):
        if not os.path.isdir(self.dir):
            return []  # never snapshotted -- "no versions", not a crash
        out = []
        for fn in os.listdir(self.dir):
            m = _VER_RE.match(fn[:-5]) if fn.endswith(".json") else None
            if m:
                out.append(fn[:-5])
        return sorted(out, key=lambda v: int(_VER_RE.match(v).group(1)))

    def _next_version(self):
        vs = self.versions()
        n = (int(_VER_RE.match(vs[-1]).group(1)) + 1) if vs else 1
        return f"v_{n:03d}"

    def _path(self, version):
        return os.path.join(self.dir, version + ".json")

    def _head_path(self):
        return os.path.join(self.dir, "HEAD")

    def head(self):
        hp = self._head_path()
        if os.path.exists(hp):
            with open(hp) as f:
                v = f.read().strip()
            if v in self.versions():
                return v
        vs = self.versions()
        return vs[-1] if vs else None

    def _set_head(self, version):
        with open(self._head_path(), "w") as f:
            f.write(version + "\n")

    # -- read/write --
    def load(self, version=None):
        version = version or self.head()
        if version is None:
            raise FileNotFoundError(f"no snapshots yet for preset {self.preset!r}")
        with open(self._path(version)) as f:
            return json.load(f)

    def snapshot(self, state, note=None):
        """Validate, assign the next version, write it, advance HEAD. Returns the version name."""
        state = copy.deepcopy(state)
        state["preset"] = self.preset
        state["schema_version"] = SCHEMA_VERSION
        if note is not None:
            state["note"] = note
        validate(state)
        version = self._next_version()
        state["version"] = version
        state["created"] = datetime.datetime.now().isoformat(timespec="seconds")
        os.makedirs(self.dir, exist_ok=True)  # first snapshot is what creates the preset dir
        with open(self._path(version), "w") as f:
            json.dump(state, f, indent=2, sort_keys=True, ensure_ascii=False)
        self._set_head(version)
        return version

    def revert(self, version, note=None):
        """Forward-only revert: write a NEW snapshot copying `version`. History is never destroyed."""
        old = self.load(version)
        old.pop("version", None)
        old.pop("created", None)
        note = note or f"revert to {version}"
        return self.snapshot(old, note=note)

    # -- diff --
    def diff(self, va, vb):
        """Structured deltas va -> vb. Returns {'preset': {...}, 'channels': {ch: {field: [old,new]}}}."""
        a, b = self.load(va), self.load(vb)
        return diff_states(a, b)

    def render(self, version=None):
        return render_state(self.load(version))


def _diff_scalar(a, b):
    return None if a == b else [a, b]


def diff_states(a, b):
    """Deltas between two state dicts (pure — no I/O). Only changed fields appear.

    One key per TIER present in either state (`channels` always, plus e.g. `virtual_channels`) —
    schema v2, 2026-07-29: a virtual-tier change used to vanish from the diff entirely (the split-
    artifact bug this module exists to prevent), since only `channels` was ever compared.
    """
    # `note`/`version`/`created` are per-snapshot labels, not comparable STATE — excluded on purpose.
    out = {"from": a.get("version"), "to": b.get("version"), "preset": {}}
    for k in ("sample_rate", "target", "roles", "provenance", "virtual_eq_ptr"):
        d = _diff_scalar(a.get(k), b.get(k))
        if d is not None:
            out["preset"][k] = d
    for tier in sorted(set(tier_names(a)) | set(tier_names(b))):
        a_rows, b_rows = a.get(tier) or {}, b.get(tier) or {}
        tier_out = {}
        for ch in sorted(set(a_rows) | set(b_rows)):
            if ch not in a_rows:
                tier_out[ch] = {"__added__": True}
                continue
            if ch not in b_rows:
                tier_out[ch] = {"__removed__": True}
                continue
            fields = {}
            for fld in CHANNEL_FIELDS:
                d = _diff_scalar(a_rows[ch].get(fld), b_rows[ch].get(fld))
                if d is not None:
                    fields[fld] = d
            if fields:
                tier_out[ch] = fields
        out[tier] = tier_out
    return out


# ── render (generated-only settings sheet) ───────────────────────────────────
def _fmt_filter(f):
    if f is None or f == "OFF":
        return "OFF"
    return f"{f['f']:g} {f.get('type', '?')} {f.get('slope', '?')}"


_STATUS_ICON = {"proposed": "🟡", "applied": "🟢", "measured": "📏"}


def _fmt_opt(v, spec="g"):
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        return format(v, spec)
    return "—" if v is None else str(v)


def render_state(state):
    """The human-applicable settings sheet, GENERATED from the source of truth.

    Never hand-edit this — edit the JSON and re-render. This is also the artifact the future
    `apply-change` gate hands the Arbiter to read at the PC-Tool screen (channel/param/old→new),
    which is what makes the compliant path the easiest path.
    """
    rate = state["sample_rate"]
    roles = state.get("roles") or {}
    lines = []
    lines.append(f"# DSP settings sheet — {state.get('preset', '?')} · {state.get('version', '(unsaved)')}")
    lines.append("")
    meta = [
        f"target: {state.get('target', '—')}",
        f"sample_rate: {rate:g} Hz (samples derived; ms is canonical)",
        f"roles: artist={roles.get('artist', '—')} · producer={roles.get('producer', '—')} · critic={roles.get('critic', '—')}",
    ]
    prov = state.get("provenance") or {}
    if prov:
        # `provenance` is documented as an object ({"decision": ...}), but real ledgers in the
        # wild carry a plain sentence instead -- rendering used to crash outright on those
        # (`'str' object has no attribute 'get'`). Free-text is the lenient half of the schema,
        # so accept both shapes rather than refuse a snapshot that is otherwise perfectly valid.
        detail = prov.get("decision", prov.get("round", "—")) if isinstance(prov, dict) else prov
        meta.append(f"provenance: {detail}")
    if state.get("note"):
        meta.append(f"note: {state['note']}")
    if state.get("created"):
        meta.append(f"created: {state['created']}")
    lines += ["- " + m for m in meta]
    lines.append("")
    lines.append("| Channel | Slot | HP | LP | Pol | TA ms | TA smp | Gain dB | Status | EQ (out / virt) |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for ch_name, ch in state["channels"].items():
        eq = ch.get("eq_ptr") or {}
        eq_s = f"{eq.get('output', '—')} / {eq.get('virtual', '—')}"
        st = ch.get("status", "proposed")
        lines.append(
            f"| {ch_name} | {ch.get('slot', '—')} | {_fmt_filter(ch['hp'])} | {_fmt_filter(ch['lp'])} "
            f"| {ch['polarity']} | {ch['ta_ms']:g} | {samples_for(ch['ta_ms'], rate)} | {ch['gain_db']:g} "
            f"| {_STATUS_ICON.get(st, '?')} {st} | {eq_s} |"
        )
    for tier in tier_names(state):
        if tier == "channels":
            continue
        rows = state.get(tier) or {}
        if not rows:
            continue
        lines.append(f"### {tier}")
        lines.append("")
        lines.append("| Row | Slot | Gain dB | TA ms | TA smp | Pol | Phase° | Mute | EQ |")
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for name, row in rows.items():
            ta = row.get("ta_ms")
            ta_smp = samples_for(ta, rate) if isinstance(ta, (int, float)) else "—"
            bands = eq_str(row.get("eq"))
            lines.append(
                f"| {name} | {row.get('slot', '—')} | {_fmt_opt(row.get('gain_db'))} "
                f"| {_fmt_opt(ta)} | {ta_smp} | {row.get('polarity', '—')} "
                f"| {_fmt_opt(row.get('phase_deg'))} | {'MUTE' if row.get('mute') else '—'} "
                f"| {' · '.join(bands) if bands else '—'} |"
            )
        lines.append("")
    verdicts = state.get("banked_ear_verdicts") or []
    if verdicts:
        lines += ["", "**Banked ear verdicts:**"] + [f"- {v}" for v in verdicts]
    lines.append("")
    return "\n".join(lines)


def render_diff(d):
    """Compact human view of diff_states() output — one section per tier that actually changed."""
    lines = [f"# diff {d.get('from')} → {d.get('to')}", ""]
    if d["preset"]:
        lines.append("**Preset-level:**")
        for k, (o, n) in d["preset"].items():
            lines.append(f"- {k}: {o!r} → {n!r}")
        lines.append("")
    any_tier = False
    for tier in sorted(k for k in d if k not in ("from", "to", "preset")):
        fields_by_ch = d[tier]
        if not fields_by_ch:
            continue
        any_tier = True
        lines.append(f"**{tier}:**")
        for ch, fields in fields_by_ch.items():
            if fields.get("__added__"):
                lines.append(f"- {ch}: ➕ added")
            elif fields.get("__removed__"):
                lines.append(f"- {ch}: ➖ removed")
            else:
                parts = [f"{fld} {o!r}→{n!r}" for fld, (o, n) in fields.items()]
                lines.append(f"- {ch}: " + " · ".join(parts))
        lines.append("")
    if not d["preset"] and not any_tier:
        lines.append("_(no changes)_")
    return "\n".join(lines) + "\n"


# ── multi-slot registry (issue #5: active-slot integrity) ─────────────────────
class Registry:
    """Which preset (slot) is ACTIVE in the physical DSP right now — the anti-cross-slot-anchoring
    pointer.

    A multi-preset processor (e.g. Helix Slot 1/2/3) invites a degrading model to anchor on the
    WRONG slot's gains: the real incident (issue #5) was tuning Slot 3 (SQ-Comp-Ref) while the top
    of a flat state table showed Slot 2 (ResoNix) numbers, so proposed HF filters were computed off
    a −8.0 dB baseline that belonged to a different slot. Each preset's snapshots already live
    physically isolated under `<root>/<preset>/` (PresetHistory); this registry adds the one missing
    thing — an explicit, machine-checked pointer to the live slot — and `render()` emits a LOUD
    banner so a top-down read hits the active slot first and can't drift to a neighbour's table.
    The apply gate (`apply.py propose`) reads this to REFUSE a change aimed at a non-active slot.
    """

    def __init__(self, root):
        # Read-only construction, same rule as `PresetHistory` above: `get_active()` on a project
        # with no `state/` yet answers "none", it doesn't materialise the tree.
        self.root = root

    def _path(self):
        return os.path.join(self.root, "registry.json")

    def list_presets(self):
        """Preset names that actually have a snapshot history under root (dirs holding v_NNN.json)."""
        out = []
        if os.path.isdir(self.root):
            for name in sorted(os.listdir(self.root)):
                d = os.path.join(self.root, name)
                if os.path.isdir(d) and any(
                        fn.endswith(".json") and _VER_RE.match(fn[:-5]) for fn in os.listdir(d)):
                    out.append(name)
        return out

    def load(self):
        p = self._path()
        if os.path.exists(p):
            with open(p) as f:
                return json.load(f)
        return {"active": None, "slots": {}}

    def _write(self, reg):
        reg["updated"] = datetime.datetime.now().isoformat(timespec="seconds")
        os.makedirs(self.root, exist_ok=True)
        with open(self._path(), "w") as f:
            json.dump(reg, f, indent=2, sort_keys=True, ensure_ascii=False)

    def get_active(self):
        return self.load().get("active")

    def set_active(self, preset):
        """Point the active slot at `preset`. Deterministic guard: it must already have a history."""
        presets = self.list_presets()
        if preset not in presets:
            raise ValueError(f"preset {preset!r} has no snapshot history under {self.root!r} "
                             f"(known: {presets or 'none'}) — seed it (history.snapshot) before "
                             f"making it the active slot")
        reg = self.load()
        reg["active"] = preset
        reg.setdefault("slots", {})
        self._write(reg)
        return preset

    def describe_slot(self, preset, label=None, note=None):
        """Attach an optional human label/desc to a slot (e.g. label='Slot 3', note='SQ-Comp-Ref')."""
        reg = self.load()
        entry = reg.setdefault("slots", {}).setdefault(preset, {})
        if label is not None:
            entry["label"] = label
        if note is not None:
            entry["note"] = note
        self._write(reg)
        return entry

    def render(self):
        return render_registry(self.root, self.load(), self.list_presets())


def render_registry(root, reg, presets):
    """LOUD active-slot banner + one isolated summary row per preset — the generated multi-slot
    `dsp-state-current` view. Generated-only (never hand-edited): a top-down read hits the ACTIVE
    banner first, so it cannot anchor on a neighbour slot's gains (issue #5)."""
    active = reg.get("active")
    slots = reg.get("slots") or {}
    lines = ["# DSP state — multi-slot registry", ""]
    if active:
        lbl = (slots.get(active) or {}).get("label")
        lines.append(f"> ⚠️ **ACTIVE SLOT IN THE DSP:** `{active}`" + (f" — {lbl}" if lbl else ""))
        lines.append("> Read and propose ONLY against this preset's section. The apply gate refuses "
                     "changes aimed at any other slot.")
    else:
        lines.append("> ⚠️ **NO ACTIVE SLOT SET** — run `state.py registry set-active <preset>` "
                     "before proposing any change.")
    lines.append("")
    if not presets:
        return "\n".join(lines + ["_(no presets have a snapshot history yet)_", ""])
    lines += ["| Slot (preset) | Active | HEAD | Target | Key gains (dB) |",
              "|---|---|---|---|---|"]
    for preset in presets:
        h = PresetHistory(root, preset)
        head = h.head()
        s = h.load(head) if head else {}
        chans = s.get("channels", {}) or {}
        gains = " · ".join(f"{c}={chans[c].get('gain_db')}" for c in list(chans)[:4]) if chans else "—"
        lbl = (slots.get(preset) or {}).get("label")
        name = preset + (f" — {lbl}" if lbl else "")
        mark = "✅" if preset == active else ""
        lines.append(f"| {name} | {mark} | {head or '—'} | {s.get('target', '—')} | {gains} |")
    lines.append("")
    return "\n".join(lines)


# ── CLI ───────────────────────────────────────────────────────────────────────
def _main(argv=None):
    p = argparse.ArgumentParser(description="Versioned hard-params DSP state")
    p.add_argument("--root", default=os.environ.get("AUTOSOUND_STATE_ROOT", "state"),
                   help="directory holding <preset>/ snapshots (project-local; env AUTOSOUND_STATE_ROOT)")
    sub = p.add_subparsers(dest="cmd")
    for name in ("log", "render", "revert"):
        sp = sub.add_parser(name)
        sp.add_argument("preset")
        if name in ("render", "revert"):
            sp.add_argument("version", nargs="?", default=None)
    sp = sub.add_parser("diff")
    sp.add_argument("preset")
    sp.add_argument("va")
    sp.add_argument("vb")
    rp = sub.add_parser("registry", help="multi-slot active-slot pointer (issue #5)")
    rp.add_argument("action", choices=["show", "set-active", "render", "describe"])
    rp.add_argument("preset", nargs="?", default=None)
    rp.add_argument("--label", default=None)
    rp.add_argument("--note", default=None)
    sub.add_parser("selftest")
    args = p.parse_args(argv)

    if args.cmd == "selftest" or args.cmd is None:
        return _selftest()
    if args.cmd == "registry":
        reg = Registry(args.root)
        if args.action == "set-active":
            print("active →", reg.set_active(args.preset))
        elif args.action == "describe":
            print(reg.describe_slot(args.preset, label=args.label, note=args.note))
        elif args.action == "render":
            print(reg.render())
        else:  # show
            print(json.dumps(reg.load(), indent=2, ensure_ascii=False))
        return 0
    h = PresetHistory(args.root, args.preset)
    if args.cmd == "log":
        for v in h.versions():
            s = h.load(v)
            head = " (HEAD)" if v == h.head() else ""
            print(f"{v}{head}  {s.get('created', '')}  {s.get('note', '')}")
    elif args.cmd == "render":
        print(h.render(args.version))
    elif args.cmd == "diff":
        print(render_diff(h.diff(args.va, args.vb)))
    elif args.cmd == "revert":
        print("wrote", h.revert(args.version))


# ── self-test ─────────────────────────────────────────────────────────────────
def _sample_state():
    """A minimal Passat-shaped state (grounded in dsp-state-current clean-slate).

    Carries `preset` itself (normally injected by `snapshot()`) so `validate()` can also be called
    directly on this fixture, as several selftest cases below do -- without it every direct
    `validate()` call raised on the missing key regardless of what it was actually trying to
    exercise (a latent gap in the pre-schema-v2 selftest)."""
    return {
        "preset": "SQ_Jazzi",
        "sample_rate": 96000,
        "target": "Jazzi",
        "roles": {"artist": "Gemini", "producer": "Claude", "critic": None},
        "provenance": {"decision": "clean-slate by-ear 2026-06-18"},
        "banked_ear_verdicts": [],
        "virtual_eq_ptr": None,
        "channels": {
            "sub":  {"slot": "K", "descr": "Subwoofer", "order": 0, "hp": {"f": 20, "type": "BE", "slope": 12},
                     "lp": {"f": 45, "type": "BW", "slope": 12}, "gain_db": -6.0,
                     "ta_ms": 5.0, "polarity": "NORM", "eq_ptr": {}, "status": "applied"},
            "w-L":  {"slot": "C", "descr": "Front L Woofer", "order": 1, "hp": {"f": 70, "type": "BW", "slope": 12},
                     "lp": {"f": 270, "type": "BW", "slope": 12}, "gain_db": -7.8,
                     "ta_ms": 5.38, "polarity": "NORM", "eq_ptr": {}, "status": "applied"},
            "tw-R": {"slot": "H", "descr": "Front R Tweeter", "order": 2, "mute": False, "off": False,
                     "hp": {"f": 5000, "type": "BE", "slope": 12},
                     "lp": "OFF", "gain_db": -6.0, "ta_ms": 4.09, "polarity": "NORM",
                     "eq_ptr": {}, "status": "applied"},
        },
        # a second tier (Helix-shaped: no crossover, phase/mute instead) -- present in every
        # fixture so validate/diff/apply are exercised tier-aware by default, not as a bolt-on.
        "virtual_channels": {
            "VFL": {"slot": "A", "order": 0, "descr": "Front L Full", "gain_db": 0.0,
                    "ta_ms": 0.0, "polarity": "NORM",
                    "eq": [{"type": "LSH", "f": 150, "gain_db": 2.5, "q": 0.71}]},
            "VFR": {"slot": "B", "order": 1, "descr": "Front R Full", "gain_db": 0.0,
                    "ta_ms": 0.0, "polarity": "NORM"},
        },
    }


def _selftest():
    import tempfile
    root = tempfile.mkdtemp(prefix="autosound_state_")
    h = PresetHistory(root, "SQ_Jazzi")

    v1 = h.snapshot(_sample_state(), note="baseline clean-slate")
    assert v1 == "v_001", v1
    assert h.head() == "v_001"
    assert h.load("v_001")["schema_version"] == SCHEMA_VERSION, "snapshot() must stamp schema_version"

    # ms is canonical; samples derive from 96 kHz (5.38 ms → 516 smp).
    assert samples_for(5.38, 96000) == 516, samples_for(5.38, 96000)
    # the SAME ms on a 48 kHz DSP is half the samples — the hazard the design guards.
    assert samples_for(5.38, 48000) == 258

    # change three things: sub polarity, w-L gain, w-L TA -- plus a VIRTUAL-tier change (VFL gain).
    s2 = h.load()
    s2["channels"]["sub"]["polarity"] = "INV"
    s2["channels"]["w-L"]["gain_db"] = -7.5
    s2["channels"]["w-L"]["ta_ms"] = 5.45
    s2["virtual_channels"]["VFL"]["gain_db"] = -1.0
    v2 = h.snapshot(s2, note="sub INV test + w-L trim + VFL gain")
    assert v2 == "v_002" and h.head() == "v_002"

    d = h.diff("v_001", "v_002")
    assert d["channels"]["sub"]["polarity"] == ["NORM", "INV"], d
    assert d["channels"]["w-L"]["gain_db"] == [-7.8, -7.5], d
    assert d["channels"]["w-L"]["ta_ms"] == [5.38, 5.45], d
    assert "tw-R" not in d["channels"], "unchanged channel must not appear in the diff"
    # schema v2: a virtual-tier change must show up in the diff too -- it used to vanish entirely
    # since diff_states only ever compared `channels` (the split-artifact bug this file exists to
    # prevent, now happening to a whole tier instead of one field).
    assert d["virtual_channels"]["VFL"]["gain_db"] == [0.0, -1.0], d
    assert "VFR" not in d["virtual_channels"], "unchanged virtual row must not appear in the diff"
    assert d["preset"] == {}, d

    # render is generated + carries derived samples and the status icon.
    r = h.render("v_001")
    assert "516" in r and "5.38" in r, r          # derived samples present
    assert "🟢 applied" in r, r
    assert "samples derived; ms is canonical" in r

    # revert is forward-only: v_003 == v_001 content, history intact.
    v3 = h.revert("v_001", note="back to baseline")
    assert v3 == "v_003" and h.head() == "v_003"
    assert h.load("v_003")["channels"]["sub"]["polarity"] == "NORM"
    assert h.versions() == ["v_001", "v_002", "v_003"], h.versions()

    # validation refuses garbage (the gate-in-embryo).
    bad = _sample_state()
    bad["channels"]["w-L"]["polarity"] = "sideways"
    try:
        h.snapshot(bad)
        raise AssertionError("snapshot accepted an invalid polarity")
    except ValueError:
        pass

    # ── new optional channel annotations (2026-07-29, autosound-tcc schema alignment) ──
    # slot/descr/order/mute/off round-trip through snapshot/load untouched, per _sample_state().
    reloaded = h.load("v_001")
    assert reloaded["channels"]["sub"]["slot"] == "K", reloaded["channels"]["sub"]
    assert reloaded["channels"]["w-L"]["descr"] == "Front L Woofer", reloaded["channels"]["w-L"]
    assert reloaded["channels"]["tw-R"]["order"] == 2, reloaded["channels"]["tw-R"]
    assert reloaded["channels"]["tw-R"]["mute"] is False, reloaded["channels"]["tw-R"]

    # a wrong type on the new fields is refused, same discipline as polarity/gain/ta above.
    bad_order = _sample_state()
    bad_order["channels"]["sub"]["order"] = "0"  # must be an int, not a numeric string
    try:
        validate(bad_order)
        raise AssertionError("validate accepted a non-int order")
    except ValueError:
        pass

    bad_mute = _sample_state()
    bad_mute["channels"]["sub"]["mute"] = "yes"  # must be a bool
    try:
        validate(bad_mute)
        raise AssertionError("validate accepted a non-bool mute")
    except ValueError:
        pass

    # `bool` subclasses `int`, so a bare isinstance(x, int) would let `true` through and sort as 1.
    bool_order = _sample_state()
    bool_order["channels"]["sub"]["order"] = True
    try:
        validate(bool_order)
        raise AssertionError("validate accepted a bool as order")
    except ValueError:
        pass

    # `role` + structured `eq` bands are legal carriable fields (the consumer UI renders both); a
    # snapshot must round-trip them, and the gate must not refuse them as unknown.
    with_eq = _sample_state()
    with_eq["channels"]["w-L"]["role"] = "woofer"
    with_eq["channels"]["w-L"]["eq"] = [
        {"type": "PK", "f": 1000, "gain_db": -9, "q": 2},
        {"type": "LSH", "f": 150, "gain_db": 2.5, "q": 0.71},
    ]
    with_eq["channels"]["w-L"]["phase_deg"] = 90
    vq = h.snapshot(with_eq, note="role + structured eq")
    back = h.load(vq)["channels"]["w-L"]
    assert back["role"] == "woofer", back
    assert back["eq"] == [
        {"type": "PK", "f": 1000, "gain_db": -9, "q": 2},
        {"type": "LSH", "f": 150, "gain_db": 2.5, "q": 0.71},
    ], back
    assert back["phase_deg"] == 90, back

    # an unknown EQ band type is a deterministic refusal, same discipline as bad polarity.
    bad_eq = _sample_state()
    bad_eq["channels"]["w-L"]["eq"] = [{"type": "XX", "f": 1000}]
    try:
        validate(bad_eq)
        raise AssertionError("validate accepted an unknown EQ band type")
    except ValueError:
        pass

    # other tiers have NO required fields (only `channels` does) -- a virtual row with just a
    # slot/descr/hidden is legal, the lenient half of the tier-aware split.
    lenient = _sample_state()
    lenient["virtual_channels"]["VFR"] = {"slot": "B", "descr": "Front R Full", "hidden": True}
    validate(lenient)  # must not raise

    # EQ display helpers: structured <-> string, including the LS/HS shorthand alias the two
    # hand-authored v1 ledgers actually use (canonical types are `EQ_TYPES`; migrate_v2.py relies
    # on this alias to upgrade them without hand-transcription).
    assert eq_band_from_str("LS 150 +2.5 Q0.71") == {
        "type": "LSH", "f": 150.0, "gain_db": 2.5, "q": 0.71}, eq_band_from_str("LS 150 +2.5 Q0.71")
    assert eq_band_str({"type": "PK", "f": 1000, "gain_db": -9, "q": 2}) == "PK 1000 -9 Q2"
    assert eq_str([{"type": "PK", "f": 1000, "gain_db": -9, "q": 2}]) == ["PK 1000 -9 Q2"]

    # the generated settings sheet gets a section for every non-`channels` tier that has rows.
    r_full = h.render(vq)
    assert "### virtual_channels" in r_full, r_full
    assert "VFL" in r_full and "LSH 150" in r_full, r_full

    # a real ledger in the wild carries `provenance` as a plain sentence, not the documented
    # {"decision": ...} object -- render used to crash on that ('str' has no attribute 'get').
    prov_str = _sample_state()
    prov_str["provenance"] = "attested-latest 2026-07-23, rebuilt from settled config"
    assert "attested-latest" in render_state(prov_str), "string provenance must render, not crash"

    # ── multi-slot registry (issue #5): active-slot pointer + LOUD banner ──
    h2 = PresetHistory(root, "ResoNix")
    h2.snapshot(_sample_state(), note="resonix baseline")     # a second slot to disambiguate
    reg = Registry(root)
    assert set(reg.list_presets()) == {"SQ_Jazzi", "ResoNix"}, reg.list_presets()
    try:
        reg.set_active("SQ_Comp_Ref")                          # no history → deterministic refusal
        raise AssertionError("set_active accepted a preset with no history")
    except ValueError:
        pass
    reg.set_active("SQ_Jazzi")
    assert reg.get_active() == "SQ_Jazzi"
    banner = reg.render()
    assert "ACTIVE SLOT IN THE DSP:** `SQ_Jazzi`" in banner, banner
    assert "ResoNix" in banner, "every slot must still be listed (isolated rows)"
    active_row = [ln for ln in banner.splitlines() if ln.startswith("| SQ_Jazzi")][0]
    assert "✅" in active_row, active_row

    print(f"selftest OK — 3 snapshots, diff caught the channels+virtual_channels changes (schema "
          f"v2 tier-aware), 5.38 ms → 516 smp @96k (258 @48k), revert forward-only (v_001→v_003), "
          f"validation rejected bad polarity + an unknown EQ type, structured EQ round-tripped "
          f"(incl. LS→LSH alias), render emitted a virtual_channels section; registry: 2 slots "
          f"isolated, active=SQ_Jazzi loud-bannered, set-active refused a history-less slot. "
          f"root={root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
